/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 附件预览
 * @param {Object} params
 * @param {string} params.id
 * @param {string} params.fileType
 **/
export const previewByGet = (params) =>
  axios.request({
    url: `/api/Attachfile/Preview`,
    method: "get",
    params: params,
    data: {}
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/Attachfile/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
