/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import { Stream } from "./interface/index.ts";
import axios from "axios";

/** 附件预览 */
export const previewByGet = (params: { id?: string; fileType?: string }) =>
  axios.request<any>({
    url: `/api/Attachfile/Preview`,
    method: "get",
    params: params,
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/Attachfile/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
