/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 公共参数控制器
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 修改公共参数信息
 * @param {UpdateComParamDictionary_In} params
 **/
export const updateComParamDictionaryByPost = (params) =>
  axios.request({
    url: `/api/ComParam/UpdateComParamDictionary`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改公共参数业绩规则信息，主键为空，新建；主键不存在，删除；主键存在，修改；
 * @param {UpdateComParamAchi_In[]} params
 **/
export const updateComParamAchiByPost = (params) =>
  axios.request({
    url: `/api/ComParam/UpdateComParamAchi`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改公共参数保留客户数规则信息，主键为空，新建；主键不存在，删除；主键存在，修改；
 * @param {UpdateComParamRetain_In[]} params
 **/
export const updateComParamRetainByPost = (params) =>
  axios.request({
    url: `/api/ComParam/UpdateComParamRetain`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改公共参数信息，参数分为三个数组，分别为参数数组字典、业绩规则和保留客户数，主键为空，新建；主键不存在，删除；主键存在，修改；
 * @param {UpdateComParam_In} params
 **/
export const updateComParamByPost = (params) =>
  axios.request({
    url: `/api/ComParam/UpdateComParam`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取公共参数信息。
 * @param {GetComParamList_In} params
 **/
export const getComParamListByPost = (params) =>
  axios.request({
    url: `/api/ComParam/GetComParamList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/ComParam/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
