/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 公共参数控制器
 * @version v1
}
**/

import {
  UpdateComParamDictionary_In,
  UpdateComParamDictionary_Out,
  UpdateComParamAchi_In,
  UpdateComParamAchi_Out,
  UpdateComParamRetain_In,
  UpdateComParamRetain_Out,
  UpdateComParam_In,
  UpdateComParam_Out,
  GetComParamList_In,
  GetComParamList_Out,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 修改公共参数信息 */
export const updateComParamDictionaryByPost = (params: UpdateComParamDictionary_In) =>
  axios.request<UpdateComParamDictionary_Out>({
    url: `/api/ComParam/UpdateComParamDictionary`,
    method: "post",
    params: {},
    data: params
  });

/** 修改公共参数业绩规则信息，主键为空，新建；主键不存在，删除；主键存在，修改； */
export const updateComParamAchiByPost = (params: UpdateComParamAchi_In[]) =>
  axios.request<UpdateComParamAchi_Out>({
    url: `/api/ComParam/UpdateComParamAchi`,
    method: "post",
    params: {},
    data: params
  });

/** 修改公共参数保留客户数规则信息，主键为空，新建；主键不存在，删除；主键存在，修改； */
export const updateComParamRetainByPost = (params: UpdateComParamRetain_In[]) =>
  axios.request<UpdateComParamRetain_Out>({
    url: `/api/ComParam/UpdateComParamRetain`,
    method: "post",
    params: {},
    data: params
  });

/** 修改公共参数信息，参数分为三个数组，分别为参数数组字典、业绩规则和保留客户数，主键为空，新建；主键不存在，删除；主键存在，修改； */
export const updateComParamByPost = (params: UpdateComParam_In) =>
  axios.request<UpdateComParam_Out>({
    url: `/api/ComParam/UpdateComParam`,
    method: "post",
    params: {},
    data: params
  });

/** 获取公共参数信息。 */
export const getComParamListByPost = (params: GetComParamList_In) =>
  axios.request<GetComParamList_Out>({
    url: `/api/ComParam/GetComParamList`,
    method: "post",
    params: {},
    data: params
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/ComParam/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
