/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 业绩管理控制器
 * @version v1
}
**/

import {
  QueryContractAchievement_IN,
  QueryContractAchievement_OUTApiTableOut,
  AuditContractReceiptRegisterAchievement_IN,
  BatchAuditContractReceiptRegisterAchievement_IN,
  RevokeAuditContractReceiptRegisterAchievement_IN,
  ContractSimple_Out,
  ContractWithReceiptRegister_Out,
  ContractReceiptRegisterAchievementAudit_Out,
  ContractReceiptRegisterInfo_Out,
  SalesDataStatistics_IN,
  SalesTargetStatistics_OUT,
  SalesDataStatistics_OUT,
  SalesRankStatistics_OUT,
  SalesProductStatistics_OUT,
  SalesContractStatistics_OUT,
  CustomerStatistics_OUT,
  TrackRecordStatistics_OUT,
  TrackingRecordRankStatistics_OUT,
  SalesAnalyseStatistics_IN,
  SalesCitysStatistics_OUT,
  SalesCountryAnalyseStatistics_IN,
  SalesCountryDetailAnalyseStatistics_OUT,
  SalesCountryRankAnalyseStatistics_OUT,
  SalesReciveCustomerSourceStatistics_OUT,
  SalesReciveContractTypeTransStatistics_OUT,
  SalesReciveCustomerSourceTransStatistics_OUT,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 根据查询条件获取合同到账登记列表 */
export const searchContractReceiptRegisterConfirmListByPost = (params: QueryContractAchievement_IN) =>
  axios.request<QueryContractAchievement_OUTApiTableOut>({
    url: `/api/ContractAchievement/SearchContractReceiptRegisterConfirmList`,
    method: "post",
    params: {},
    data: params
  });

/** 确认合同到账登记业绩审核信息 */
export const auditContractReceiptRegisterAchievementByPost = (params: AuditContractReceiptRegisterAchievement_IN) =>
  axios.request<any>({
    url: `/api/ContractAchievement/AuditContractReceiptRegisterAchievement`,
    method: "post",
    params: {},
    data: params
  });

/** 批量确认合同到账登记业绩审核信息 */
export const batchAuditContractReceiptRegisterAchievementByPost = (
  params: BatchAuditContractReceiptRegisterAchievement_IN
) =>
  axios.request<any>({
    url: `/api/ContractAchievement/BatchAuditContractReceiptRegisterAchievement`,
    method: "post",
    params: {},
    data: params
  });

/** 撤销合同到账登记业绩审核信息(状态为确认、有疑问才可以) */
export const revokeContractReceiptRegisterAchievementByPost = (
  params: RevokeAuditContractReceiptRegisterAchievement_IN
) =>
  axios.request<any>({
    url: `/api/ContractAchievement/RevokeContractReceiptRegisterAchievement`,
    method: "post",
    params: {},
    data: params
  });

/** 根据合同Id获取到账登记的合同信息 */
export const getContractInfoByContractIdByPost = (params: { contractId?: string }) =>
  axios.request<ContractSimple_Out>({
    url: `/api/ContractAchievement/GetContractInfoByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据到账登记表Id获取合同到账登记的合同信息和合同到账登记信息 */
export const getContractInfoByContractReceiptRegisterIdByPost = (params: { contractReceiptRegisterId?: string }) =>
  axios.request<ContractWithReceiptRegister_Out>({
    url: `/api/ContractAchievement/GetContractInfoByContractReceiptRegisterId`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据到账登记审核表id获取合同到账登记业绩审核确认信息 */
export const getContractReceiptRegisterAchievementAuditByIdByPost = (params: {
  contractReceiptRegisterAuditId?: string;
}) =>
  axios.request<ContractReceiptRegisterAchievementAudit_Out>({
    url: `/api/ContractAchievement/GetContractReceiptRegisterAchievementAuditById`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据到账登记表Id获取业绩确认详情信息（销售用） */
export const getInfoByContractReceiptRegisterIdByPost = (params: { contractReceiptRegisterId?: string }) =>
  axios.request<ContractReceiptRegisterInfo_Out>({
    url: `/api/ContractAchievement/GetInfoByContractReceiptRegisterId`,
    method: "post",
    params: params,
    data: {}
  });

/** （组织）客户数据-销售目标统计 */
export const salesTargetStatisticsByPost = (params: SalesDataStatistics_IN) =>
  axios.request<SalesTargetStatistics_OUT>({
    url: `/api/ContractAchievement/SalesTargetStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** （个人-组织）客户数据-销售业绩 (包含同比环比) */
export const salesDataStatisticsByPost = (params: SalesDataStatistics_IN) =>
  axios.request<SalesDataStatistics_OUT>({
    url: `/api/ContractAchievement/SalesDataStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** （组织）客户数据-业绩排行 */
export const salesOrgRankStatisticsByPost = (params: SalesDataStatistics_IN) =>
  axios.request<SalesRankStatistics_OUT>({
    url: `/api/ContractAchievement/SalesOrgRankStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** （个人）客户数据-业绩排行 */
export const salesUserRankStatisticsByPost = (params: SalesDataStatistics_IN) =>
  axios.request<SalesRankStatistics_OUT>({
    url: `/api/ContractAchievement/SalesUserRankStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 客户数据-产品业绩 */
export const salesProductStatisticsByPost = (params: SalesDataStatistics_IN) =>
  axios.request<SalesProductStatistics_OUT>({
    url: `/api/ContractAchievement/SalesProductStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 客户数据-合同统计 */
export const salesContractStatisticsByPost = (params: SalesDataStatistics_IN) =>
  axios.request<SalesContractStatistics_OUT>({
    url: `/api/ContractAchievement/SalesContractStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 客户数据-客户统计 */
export const customerStatisticsByPost = (params: SalesDataStatistics_IN) =>
  axios.request<CustomerStatistics_OUT>({
    url: `/api/ContractAchievement/CustomerStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 客户数据-跟踪统计 */
export const trackRecordStatisticsByPost = (params: SalesDataStatistics_IN) =>
  axios.request<TrackRecordStatistics_OUT>({
    url: `/api/ContractAchievement/TrackRecordStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 客户数据-跟踪排行 */
export const trackingRecordRankStatisticsByPost = (params: SalesDataStatistics_IN) =>
  axios.request<TrackingRecordRankStatistics_OUT>({
    url: `/api/ContractAchievement/TrackingRecordRankStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 销售分析-客户（按合同计算：新增合同和续约合同都各自算一个新客户）地域分布 */
export const salesCitysStatisticsByPost = (params: SalesAnalyseStatistics_IN) =>
  axios.request<SalesCitysStatistics_OUT>({
    url: `/api/ContractAchievement/SalesCitysStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 销售分析-客户（签过合同且未作废的算签约客户）地域分布-国家详情 */
export const salesCountryDetailAnalyseStatisticsByPost = (params: SalesCountryAnalyseStatistics_IN) =>
  axios.request<SalesCountryDetailAnalyseStatistics_OUT>({
    url: `/api/ContractAchievement/SalesCountryDetailAnalyseStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 销售分析-客户（签过合同且未作废的算签约客户）地域分布-国家排行 */
export const salesCountryRankAnalyseStatisticsByPost = (params: SalesCountryAnalyseStatistics_IN) =>
  axios.request<SalesCountryRankAnalyseStatistics_OUT>({
    url: `/api/ContractAchievement/SalesCountryRankAnalyseStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 销售分析-到账客户（）来源 */
export const salesReciveCustomerSourceStatisticsByPost = (params: SalesAnalyseStatistics_IN) =>
  axios.request<SalesReciveCustomerSourceStatistics_OUT>({
    url: `/api/ContractAchievement/SalesReciveCustomerSourceStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 销售分析-到账客户（）合同转化率 */
export const salesReciveContractTypeTransStatisticsByPost = (params: SalesAnalyseStatistics_IN) =>
  axios.request<SalesReciveContractTypeTransStatistics_OUT>({
    url: `/api/ContractAchievement/SalesReciveContractTypeTransStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 销售分析-到账客户（）来源转化率 */
export const salesReciveCustomerSourceTransStatisticsByPost = (params: SalesAnalyseStatistics_IN) =>
  axios.request<SalesReciveCustomerSourceTransStatistics_OUT>({
    url: `/api/ContractAchievement/SalesReciveCustomerSourceTransStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/ContractAchievement/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
