/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 添加合同发票申请
 * @param {FormData} params
 **/
export const addContractInvoiceApplByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/AddContractInvoiceAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改合同发票申请
 * @param {FormData} params
 **/
export const updateContractInvoiceApplByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/UpdateContractInvoiceAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 审核合同发票申请
 * @param {FormData} params
 **/
export const auditContractInvoiceApplByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/AuditContractInvoiceAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据发票申请Id获取合同基本信息和发票申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractInfoAndInvoiceApplByInvoiceApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractInfoAndInvoiceApplByInvoiceApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据查询条件获取合同发票申请列表
 * @param {SearchContractInvoiceAuditList_In} params
 **/
export const searchContractInvoiceAuditListByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/SearchContractInvoiceAuditList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据合同Id获取合同信息和到账信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractAndReceiptByContractIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractAndReceiptByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同发票申请Id获取合同发票信息和审核信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractInvoiceAndAuditByContractInvoiceApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractInvoiceAndAuditByContractInvoiceApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同发票申请Id获取合同信息和发票信息、发票申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractInfoAndInvoiceInfoByInvoiceApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractInfoAndInvoiceInfoByInvoiceApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 发起退票
 * @param {ContractRefundInvoice_In} params
 **/
export const initiateContractRefundInvoiceByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/InitiateContractRefundInvoice`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 审核退票信息
 * @param {AuditContractRefundInvoice_In} params
 **/
export const auditContractRefundInvoiceByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/AuditContractRefundInvoice`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取合同发票申请列表
 * @param {SearchContractInvoiceApplList_In} params
 **/
export const searchContractInvoiceApplListByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/SearchContractInvoiceApplList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据合同发票申请Id获取合同发票申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractInvoiceApplByIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractInvoiceApplById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 操作退票 (红冲)上传退票信息
 * @param {FormData} params
 **/
export const operateContractRefundInvoiceByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/OperateContractRefundInvoice`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据退票id获取退票信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractRefundInvoiceByIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractRefundInvoiceById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同发票申请Id获取合同信息和发票信息、发票申请信息、退票信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractInfoAndInvoiceInfoAndRefundInvoiceInfoByInvoiceApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractInfoAndInvoiceInfoAndRefundInvoiceInfoByInvoiceApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同发票申请Id获取发票信息、发票申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractInvoiceApplAndInvoiceInfoByInvoiceApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractInvoiceApplAndInvoiceInfoByInvoiceApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据发票申请id获取退票信息列表
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractRefundInvoiceListByInvoiceApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractRefundInvoiceListByInvoiceApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 作废合同发票申请信息，当开票状态为全部开票、部分开票时，可操作。
 * @param {Object} params
 * @param {string} params.id
 **/
export const voidContractInvoiceApplByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/VoidContractInvoiceAppl`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 撤销合同发票申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const revokeContractInvoiceApplByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/RevokeContractInvoiceAppl`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 撤销合同发票提交申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const revokeContractInvoiceApplSubmitByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/RevokeContractInvoiceApplSubmit`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同id获取已开票金额
 * @param {Object} params
 * @param {string} params.id
 **/
export const getInvoicedAmountByContractIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetInvoicedAmountByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 删除合同发票申请信息，当开票状态为草稿、作废、拒绝时，可删除。
 * @param {Object} params
 * @param {string} params.id
 **/
export const deleteContractInvoiceApplByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/DeleteContractInvoiceAppl`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 催票，当开票状态为申请时，可操作。
 * @param {ReminderContractInvoiceAppl_IN} params
 **/
export const reminderContractInvoiceApplByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/ReminderContractInvoiceAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 确认签收，当开票状态为全部开票、部分开票时，可操作
 * @param {Object} params
 * @param {string} params.id
 **/
export const signReceivingContractInvoiceApplByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/SignReceivingContractInvoiceAppl`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同发票申请Id获取发票信息、发票申请信息、退票信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractInvoiceInfoAndRefundInvoiceInfoByInvoiceApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractInvoiceInfoAndRefundInvoiceInfoByInvoiceApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同发票申请Id获取发票的发票编号信息
 * @param {Object} params
 * @param {string} params.invoiceApplId
 **/
export const getInvoiceInfoByInvoiceApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetInvoiceInfoByInvoiceApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同Id获取发票信息
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const getInvoiceInfoByContractIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetInvoiceInfoByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同Id和开票时间获取发票信息列表
 * @param {ContractInvoiceList_In} params
 **/
export const getContractInvoiceListByContractIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractInvoiceListByContractId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据客户Id和开票时间获取发票信息列表
 * @param {ContractInvoiceList_CustomerId_In} params
 **/
export const getContractInvoiceListByCustomerIdByPost = (params) =>
  axios.request({
    url: `/api/ContractInvoice/GetContractInvoiceListByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/ContractInvoice/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
