/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 根据查询条件获取合同服务信息慧思学院申请信息列表
 * @param {SearchContractProductServiceInfoCollegeApplList_In} params
 **/
export const searchContractProductServiceInfoCollegeApplListByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoCollege/SearchContractProductServiceInfoCollegeApplList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务申请信息_慧思学院信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractServiceInfoApplyInfoCollegeByApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoCollege/GetContractServiceInfoApplyInfoCollegeByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 撤销合同服务信息慧思学院申请审核信息
 * @param {OperateContractProductServiceInfoCollegeAudit_In} params
 **/
export const revokeContractProductServiceInfoCollegeAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoCollege/RevokeContractProductServiceInfoCollegeAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 作废合同服务信息慧思学院申请审核信息
 * @param {OperateContractProductServiceInfoCollegeAudit_In} params
 **/
export const voidContractProductServiceInfoCollegeAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoCollege/VoidContractProductServiceInfoCollegeAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除合同服务信息慧思学院申请信息
 * @param {OperateContractProductServiceInfoCollegeAudit_In} params
 **/
export const deleteContractProductServiceInfoCollegeAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoCollege/DeleteContractProductServiceInfoCollegeAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 设置慧思学院用户状信息
 * @param {SetCollegeContacts_In} params
 **/
export const setCollegeContactsByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoCollege/SetCollegeContacts`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请Id批量修改服务用户状态-启用/停用
 * @param {SetContractServiceInfoCollegeContactsByApplyIds_In} params
 **/
export const setContractServiceInfoCollegeContactsByApplyIdsByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoCollege/SetContractServiceInfoCollegeContactsByApplyIds`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务信息_慧思学院信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractServiceInfoCollegeByApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoCollege/GetContractServiceInfoCollegeByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同产品信息表id获取合同服务信息_慧思学院信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractServiceInfoCollegeByContractProductInfoIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoCollege/GetContractServiceInfoCollegeByContractProductInfoId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 验证开通账号是否存在重复
 * @param {CheckHasSameValidContacts_In} params
 **/
export const checkHasSameValidContactsByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoCollege/CheckHasSameValidContacts`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/ContractServiceInfoCollege/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
