/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 添加纸质合同申领信息
 * @param {AddContractPaperApply_In} params
 **/
export const addContractPaperApplyByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/AddContractPaperApply`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改纸质合同申领信息
 * @param {UpdateContractPaperApply_In} params
 **/
export const updateContractPaperApplyByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/UpdateContractPaperApply`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除纸质合同申领信息
 * @param {Object} params
 * @param {string} params.Ids
 **/
export const deleteContractPaperApplyByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/DeleteContractPaperApply`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 撤销纸质合同申领信息
 * @param {Object} params
 * @param {string} params.Ids
 **/
export const revokeContractPaperApplyByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/RevokeContractPaperApply`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据查询条件获取纸质合同申领信息列表
 * @param {SearchContractPaperApplyList_In} params
 **/
export const searchContractPaperApplyListByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/SearchContractPaperApplyList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据纸质合同申领信息Id获取纸质合同申领信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractPaperApplyInfoByIdByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/GetContractPaperApplyInfoById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据纸质合同申领id获取合同信息列表
 * @param {GetContractByContractPaperApplyId_In} params
 **/
export const getContractByContractPaperApplyIdByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/GetContractByContractPaperApplyId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据纸质合同申领id获取纸质合同分发列表信息
 * @param {GetContractPaperDistributeByContractPaperApplyId_In} params
 **/
export const getContractPaperDistributeByContractPaperApplyIdByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/GetContractPaperDistributeByContractPaperApplyId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取纸质合同申领信息列表
 * @param {SearchContractPaperAuditList_In} params
 **/
export const searchContractPaperAuditListByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/SearchContractPaperAuditList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 审核纸质合同申领信息
 * @param {AuditContractPaperApply_In} params
 **/
export const auditContractPaperApplyByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/AuditContractPaperApply`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 撤销审核纸质合同申领信息
 * @param {Object} params
 * @param {string} params.Ids
 **/
export const revokeAuditContractPaperApplyByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/RevokeAuditContractPaperApply`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 作废审核纸质合同申领信息
 * @param {Object} params
 * @param {string} params.Ids
 **/
export const voidAuditContractPaperApplyByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/VoidAuditContractPaperApply`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 获取纸质合同待分发列表数据
 * @param {GetContractPaperTobeDistributeList_In} params
 **/
export const getContractPaperTobeDistributeListByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/GetContractPaperTobeDistributeList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 待分发列表页面头部纸质合同申领明细的合同版本及实发份数
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractPaperTobeDistributeDetailListByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/GetContractPaperTobeDistributeDetailList`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据申领Id获取已分发的纸质合同分发数据
 * @param {GetContractPaperDistributeList_In} params
 **/
export const getContractPaperDistributeListByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/GetContractPaperDistributeList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 维护(新增保存或修改)纸质合同分发信息
 * @param {DistributeContractPaper_In[]} params
 **/
export const distributeContractPaperByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/DistributeContractPaper`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据纸质合同申领信息Id获取纸质合同申领信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractPaperApplyInfoByAuditIdByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/GetContractPaperApplyInfoByAuditId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据纸质合同申领id获取合同信息列表
 * @param {GetContractByContractPaperApplyId_In} params
 **/
export const getContractByContractPaperAuditIdByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/GetContractByContractPaperAuditId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据纸质合同申领id获取纸质合同分发列表信息
 * @param {GetContractPaperDistributeByContractPaperApplyId_In} params
 **/
export const getContractPaperDistributeByContractPaperAuditIdByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/GetContractPaperDistributeByContractPaperAuditId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取当前用户可以使用的纸质合同号
 * @param {Object} params
 * @param {string} params.contractPaperEntityId
 **/
export const getContractPaperEntitiesByRecipientIdByPost = (params) =>
  axios.request({
    url: `/api/ContractPaper/GetContractPaperEntitiesByRecipientId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/ContractPaper/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
