/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 添加到账登记
 * @param {AddReceiptRegister_In} params
 **/
export const addReceiptRegisterByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/AddReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改到账登记
 * @param {UpdateReceiptRegister_In} params
 **/
export const updateReceiptRegisterByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/UpdateReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 到账登记复核
 * @param {AuditContractReceiptRegister_In} params
 **/
export const auditContractReceiptRegisterByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/AuditContractReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取待锁定到账登记信息
 * @param {GetTobeLockContractReceiptRegister_In} params
 **/
export const getTobeLockContractReceiptRegisterByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetTobeLockContractReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取已锁定到账登记信息
 * @param {GetLockedContractReceiptRegister_In} params
 **/
export const getLockedContractReceiptRegisterByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetLockedContractReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 锁定合同到账登记业绩审核信息
 * @param {string[]} params
 **/
export const lockContractReceiptRegisterAchievementByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/LockContractReceiptRegisterAchievement`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 解除锁定合同到账登记业绩审核信息
 * @param {string[]} params
 **/
export const unLockContractReceiptRegisterAchievementByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/UnLockContractReceiptRegisterAchievement`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 添加项目其他信息
 * @param {ProjectInfoOtherItem_In} params
 **/
export const addProjectInfoOtherItemByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/AddProjectInfoOtherItem`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取项目其他信息列表
 **/
export const getProjectInfoOtherItemListByPost = () =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetProjectInfoOtherItemList`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 获取项目信息列表
 **/
export const getProjectInfoListByPost = () =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetProjectInfoList`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 根据匹配待登记Id获取匹配待登记信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getMatchingRegisteredByIdByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetMatchingRegisteredById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据匹配待登记Id拆分匹配待登记信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const splitMatchingRegisteredByIdByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/SplitMatchingRegisteredById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据查询条件获取合同到账登记列表
 * @param {SearchContractReceiptRegisterList_In} params
 **/
export const searchContractReceiptRegisterListByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/SearchContractReceiptRegisterList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据到账登记Id获取到账登记信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getReceiptRegisterByIdByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetReceiptRegisterById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 撤销到账登记，当确认状态为待确认、待复核、被驳回时，可返回上一个状态，返回后可重新进行操作。
 * @param {Object} params
 * @param {string} params.id
 **/
export const revokeReceiptRegisterByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/RevokeReceiptRegister`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同id获取到账登记信息
 * @param {GetReceiptRegisterByContractId_In} params
 **/
export const getReceiptRegisterByContractIdByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetReceiptRegisterByContractId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据客户id和到账日期获取到账登记信息
 * @param {GetReceiptRegisterByCustomerId_In} params
 **/
export const getReceiptRegisterByCustomerIdByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetReceiptRegisterByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据合同id获取回款金额和退款信息
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const getReceiptRegisterArrivalAmountInfoByContractIdByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetReceiptRegisterArrivalAmountInfoByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据到账登记表Id获取业绩确认详情信息（登记/复核用）
 * @param {Object} params
 * @param {string} params.contractReceiptRegisterId
 **/
export const getInfoByContractReceiptRegisterIdForAdminByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetInfoByContractReceiptRegisterIdForAdmin`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 获取待确认到账登记信息
 * @param {GetTobeConfirmedContractReceiptRegister_In} params
 **/
export const getTobeConfirmedContractReceiptRegisterByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetTobeConfirmedContractReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据合同id获取已确认到账登记款项信息
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const getConfirmedReceiptDetailsByContractIdByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/GetConfirmedReceiptDetailsByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 删除到账登记，当状态为待登记可进行操作
 * @param {Object} params
 * @param {string} params.id
 * @param {number} params.type
 **/
export const deleteReceiptRegisterByPost = (params) =>
  axios.request({
    url: `/api/ContractReceiptRegister/DeleteReceiptRegister`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/ContractReceiptRegister/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
