/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import {
  SearchContractProductServiceInfoOtherDataApplList_In,
  SearchContractProductServiceInfoOtherDataApplList_OutApiTableOut,
  GetContractServiceInfoApplyInfoOtherDataByApplId_Out,
  OperateContractProductServiceInfoOtherDataAudit,
  GetContractServiceInfoOtherDataByApplId_Out,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 根据查询条件获取合同服务信息其他数据申请信息列表 */
export const searchContractProductServiceInfoOtherDataApplListByPost = (
  params: SearchContractProductServiceInfoOtherDataApplList_In
) =>
  axios.request<SearchContractProductServiceInfoOtherDataApplList_OutApiTableOut>({
    url: `/api/ContractServiceInfoOtherData/SearchContractProductServiceInfoOtherDataApplList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据申请id获取合同服务申请信息_其他数据信息 */
export const getContractServiceInfoApplyInfoOtherDataByApplIdByPost = (params: { Id?: string }) =>
  axios.request<GetContractServiceInfoApplyInfoOtherDataByApplId_Out>({
    url: `/api/ContractServiceInfoOtherData/GetContractServiceInfoApplyInfoOtherDataByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/** 撤销合同服务信息其他数据申请审核信息 */
export const revokeContractProductServiceInfoOtherDataAuditByPost = (
  params: OperateContractProductServiceInfoOtherDataAudit
) =>
  axios.request<any>({
    url: `/api/ContractServiceInfoOtherData/RevokeContractProductServiceInfoOtherDataAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 作废合同服务信息其他数据申请审核信息 */
export const voidContractProductServiceInfoOtherDataAuditByPost = (
  params: OperateContractProductServiceInfoOtherDataAudit
) =>
  axios.request<any>({
    url: `/api/ContractServiceInfoOtherData/VoidContractProductServiceInfoOtherDataAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 删除合同服务信息其他数据申请信息 */
export const deleteContractProductServiceInfoOtherDataAuditByPost = (
  params: OperateContractProductServiceInfoOtherDataAudit
) =>
  axios.request<any>({
    url: `/api/ContractServiceInfoOtherData/DeleteContractProductServiceInfoOtherDataAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 根据申请id获取合同服务信息_其他数据信息 */
export const getContractServiceInfoOtherDataByApplIdByPost = (params: { Id?: string }) =>
  axios.request<GetContractServiceInfoOtherDataByApplId_Out>({
    url: `/api/ContractServiceInfoOtherData/GetContractServiceInfoOtherDataByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/ContractServiceInfoOtherData/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
