/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 审核合同服务信息邓白氏申请信息
 * @param {FormData} params
 **/
export const auditContractProductServiceInfoDbApplByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/AuditContractProductServiceInfoDBAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 审核合同服务信息环球搜申请信息
 * @param {AuditContractProductServiceInfoGlobalSearchAppl_In} params
 **/
export const auditContractProductServiceInfoGlobalSearchApplByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/AuditContractProductServiceInfoGlobalSearchAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 审核合同服务信息慧思学院申请信息
 * @param {AuditContractProductServiceInfoCollegeAppl_In} params
 **/
export const auditContractProductServiceInfoCollegeApplByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/AuditContractProductServiceInfoCollegeAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 登记合同服务信息期刊邮寄的快递信息
 * @param {FormData} params
 **/
export const registerContractProductServiceInfoMailingByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/RegisterContractProductServiceInfoMailing`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 审核合同服务信息其他数据申请信息
 * @param {AuditContractProductServiceInfoOtherDataAppl_In} params
 **/
export const auditContractProductServiceInfoOtherDataApplByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/AuditContractProductServiceInfoOtherDataAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取合同服务信息环球慧思申请信息列表
 * @param {SearchContractProductServiceInfoGtisAppl_IN} params
 **/
export const searchContractProductServiceInfoGtisApplListByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/SearchContractProductServiceInfoGtisApplList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务信息_环球慧思信息（申请信息+在服信息）
 * @param {Object} params
 * @param {string} params.applId
 **/
export const getContractServiceInfoGtisByApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/GetContractServiceInfoGtisByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据申请id获取环球慧思用户信息列表
 * @param {Object} params
 * @param {string} params.applId
 **/
export const getContractServiceInfoGtisUserByApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/GetContractServiceInfoGtisUserByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 设置环球慧思用户状态信息(启用/停用)
 * @param {SetContractServiceInfoGtisUser_IN} params
 **/
export const setContractServiceInfoGtisUserByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/SetContractServiceInfoGtisUser`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 启用/停用环球慧思产品中所有账户
 * @param {SetContractServiceInfoGtisUserAll_IN} params
 **/
export const setContractServiceInfoGtisUserAllByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/SetContractServiceInfoGtisUserAll`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 审核合同服务信息环球慧思申请信息
 * @param {AuditContractProductServiceInfoGtisAppl_IN} params
 **/
export const auditContractProductServiceInfoGtisApplByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/AuditContractProductServiceInfoGtisAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 撤销合同服务信息环球慧思申请审核信息 10.9 gtis系统不支持撤销，暂时取消撤销功能
 * @param {Object} params
 * @param {string} params.applId
 **/
export const revokeContractProductServiceInfoGtisAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractProductService/RevokeContractProductServiceInfoGtisAudit`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/ContractProductService/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
