/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 根据查询条件获取合同服务信息期刊邮寄申请信息列表
 * @param {SearchContractProductServiceInfoProjectApplList_In} params
 **/
export const searchContractProductServiceInfoProjectApplListByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoProject/SearchContractProductServiceInfoProjectApplList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务申请信息_期刊邮寄信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractServiceInfoApplyInfoProjectByApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoProject/GetContractServiceInfoApplyInfoProjectByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 作废合同服务期刊邮寄申请信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const voidContractProductServiceProjectInfoByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoProject/VoidContractProductServiceProjectInfo`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 删除合同服务期刊邮寄申请信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const deleteContractProductServiceProjectInfoByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoProject/DeleteContractProductServiceProjectInfo`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 修改合同服务期刊邮寄申请信息
 * @param {UpdateContractProductServiceProjectInfo_In} params
 **/
export const updateContractProductServiceProjectInfoByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoProject/UpdateContractProductServiceProjectInfo`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务信息_期刊邮寄信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractServiceInfoProjectByApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoProject/GetContractServiceInfoProjectByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同Id和审核日期获取发刊信息列表
 * @param {ContractProductServiceinfoProjectList_In} params
 **/
export const getContractProductServiceinfoProjectListByContractIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoProject/GetContractProductServiceinfoProjectListByContractId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据客户Id和审核日期获取发刊信息列表
 * @param {ContractProductServiceinfoProjectList_CustomerId_In} params
 **/
export const getContractProductServiceinfoProjectListByCustomerIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoProject/GetContractProductServiceinfoProjectListByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 下载期刊邮寄批量导入模板
 **/
export const downloadMailingExcelTemplateByPost = () =>
  axios.request({
    url: `/api/ContractServiceInfoProject/DownloadMailingExcelTemplate`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 上传期刊邮寄批量导入模板
 * @param {FormData} params
 **/
export const uploadMailingTemplateByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoProject/UploadMailingTemplate`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 批量登记合同服务信息期刊邮寄的快递信息
 * @param {BatchRegisterContractProductServiceInfoMailing_In[]} params
 **/
export const batchRegisterContractProductServiceInfoMailingByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoProject/BatchRegisterContractProductServiceInfoMailing`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/ContractServiceInfoProject/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
