/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description GTIS临时账号创建
 * @param {ContractServiceInfoTemporaryAccount_IN} params
 **/
export const addContractServiceInfoTemporaryAccountByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo/AddContractServiceInfoTemporaryAccount`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除临时账号信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const deleteContractServiceInfoTemporaryAccountByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo/DeleteContractServiceInfoTemporaryAccount`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 变更合同服务信息临时账号状态信息
 * @param {Object} params
 * @param {string} params.id
 * @param {number} params.state
 **/
export const updateContractServiceInfoTemporaryAccountStateByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo/UpdateContractServiceInfoTemporaryAccountState`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 延期合同服务信息临时账号信息
 * @param {Object} params
 * @param {string} params.id
 * @param {number} params.duration
 **/
export const delayContractServiceInfoTemporaryAccountByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo/DelayContractServiceInfoTemporaryAccount`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 获取延期合同服务信息临时账号信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getDelayContractServiceInfoTemporaryAccountListByIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo/GetDelayContractServiceInfoTemporaryAccountListById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据查询条件获取合同服务信息临时账号信息列表
 * @param {SearchContractServiceInfoTemporaryAccountList_In} params
 **/
export const searchContractServiceInfoTemporaryAccountListByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo/SearchContractServiceInfoTemporaryAccountList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据Id获取合同服务信息临时账号信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractServiceInfoTemporaryAccountByIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo/GetContractServiceInfoTemporaryAccountById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据客户名称获取用户私有池客户信息
 * @param {Object} params
 * @param {string} params.customerName
 **/
export const getPrivateCustomerInfoByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo/GetPrivateCustomerInfo`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据临时账号Id获取合同服务信息临时账号用户信息
 * @param {Object} params
 * @param {string} params.serviceInfoTemporaryAccountID
 **/
export const getTemporaryAccountUserByTemporaryAccountIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo/GetTemporaryAccountUserByTemporaryAccountID`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 获取当天开通演示账号剩余个数
 **/
export const getContractServiceInfoTemporaryAccountLeftOpenTimesByPost = () =>
  axios.request({
    url: `/api/ContractServiceInfo/GetContractServiceInfoTemporaryAccountLeftOpenTimes`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/ContractServiceInfo/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
