/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 合同管理 - 海外IP备案控制器
 * @version v1
}
**/

import {
  SearchIPKeepRecordList_In,
  SearchIPKeepRecordListNew_OutApiTableOut,
  GetIPKeepRecordById_In,
  GetIPKeepRecordByIdNew_Out,
  AddIPKeepRecordApply_Out,
  UpdateIPKeepRecordApply_Out,
  DeleteIPKeepRecord_In,
  DeleteIPKeepRecord_Out,
  RevokeIPKeepRecordApply_In,
  RevokeIPKeepRecordApply_Out,
  VoidIPKeepRecordApply_In,
  VoidIPKeepRecordApply_Out,
  AuditIPKeepRecordApply_In,
  AuditIPKeepRecordApply_Out,
  SearchIPKeepRecordApplyList_In,
  SearchIPKeepRecordApplyList_OutApiTableOut,
  GetGtisUserByAccountCategory_In,
  GetGtisUserByAccountCategory_OutApiTableOut,
  Province_In,
  Province_OUT,
  City_In,
  City_OUT,
  SearchSelectContractList_In,
  SearchSelectContractList_OutApiTableOut,
  GetContractInfoById_In,
  Contract_Info,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 根据查询条件获取海外IP备案列表。 */
export const searchIpKeepRecordListByPost = (params: SearchIPKeepRecordList_In) =>
  axios.request<SearchIPKeepRecordListNew_OutApiTableOut>({
    url: `/api/ContractOverseasIPRecord/SearchIPKeepRecordList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件获取海外IP备案审核列表。 */
export const searchIpKeepRecordApplyListByPost = (params: SearchIPKeepRecordList_In) =>
  axios.request<SearchIPKeepRecordListNew_OutApiTableOut>({
    url: `/api/ContractOverseasIPRecord/SearchIPKeepRecordApplyList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据IP备案Id获取IP备案信息。 */
export const getIpKeepRecordByIdByPost = (params: GetIPKeepRecordById_In) =>
  axios.request<GetIPKeepRecordByIdNew_Out>({
    url: `/api/ContractOverseasIPRecord/GetIPKeepRecordById`,
    method: "post",
    params: {},
    data: params
  });

/** 添加IP备案申请信息。 */
export const addIpKeepRecordApplyByPost = (params: FormData) =>
  axios.request<AddIPKeepRecordApply_Out>({
    url: `/api/ContractOverseasIPRecord/AddIPKeepRecordApply`,
    method: "post",
    params: {},
    data: params
  });

/** 修改IP备案申请信息。 */
export const updateIpKeepRecordApplyByPost = (params: FormData) =>
  axios.request<UpdateIPKeepRecordApply_Out>({
    url: `/api/ContractOverseasIPRecord/UpdateIPKeepRecordApply`,
    method: "post",
    params: {},
    data: params
  });

/** 删除IP备案信息，当备案状态为通过、拒绝、作废时，可操作删除。验证数据权限。 */
export const deleteIpKeepRecordByPost = (params: DeleteIPKeepRecord_In) =>
  axios.request<DeleteIPKeepRecord_Out>({
    url: `/api/ContractOverseasIPRecord/DeleteIPKeepRecord`,
    method: "post",
    params: {},
    data: params
  });

/** 撤销IP备案申请信息，当备案状态为通过、拒绝、作废时，可操作返回到上一个状态。验证数据权限 */
export const revokeIpKeepRecordApplyByPost = (params: RevokeIPKeepRecordApply_In) =>
  axios.request<RevokeIPKeepRecordApply_Out>({
    url: `/api/ContractOverseasIPRecord/RevokeIPKeepRecordApply`,
    method: "post",
    params: {},
    data: params
  });

/** 作废IP备案信息，当备案状态为通过、已提交时，可对申请备案信息进行作废处理 */
export const voidIpKeepRecordApplyByPost = (params: VoidIPKeepRecordApply_In) =>
  axios.request<VoidIPKeepRecordApply_Out>({
    url: `/api/ContractOverseasIPRecord/VoidIPKeepRecordApply`,
    method: "post",
    params: {},
    data: params
  });

/** 审核IP备案申请信息。 */
export const auditIpKeepRecordApplyByPost = (params: AuditIPKeepRecordApply_In) =>
  axios.request<AuditIPKeepRecordApply_Out>({
    url: `/api/ContractOverseasIPRecord/AuditIPKeepRecordApply`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件获取海外IP备案申请列表。 */
export const searchIpKeepRecordApplyListOldByPost = (params: SearchIPKeepRecordApplyList_In) =>
  axios.request<SearchIPKeepRecordApplyList_OutApiTableOut>({
    url: `/api/ContractOverseasIPRecord/SearchIPKeepRecordApplyListOld`,
    method: "post",
    params: {},
    data: params
  });

/** 根据账号类别获取Gtis用户列表 */
export const getGtisUserByAccountCategoryByPost = (params: GetGtisUserByAccountCategory_In) =>
  axios.request<GetGtisUserByAccountCategory_OutApiTableOut>({
    url: `/api/ContractOverseasIPRecord/GetGtisUserByAccountCategory`,
    method: "post",
    params: {},
    data: params
  });

/** 根据国家Id获取地址信息（省级别） */
export const getAddressProvinceByPost = (params: Province_In) =>
  axios.request<Province_OUT[]>({
    url: `/api/ContractOverseasIPRecord/GetAddress_Province`,
    method: "post",
    params: {},
    data: params
  });

/** 根据省Id获取地址信息(市级别) */
export const getAddressCityByPost = (params: City_In) =>
  axios.request<City_OUT[]>({
    url: `/api/ContractOverseasIPRecord/GetAddress_City`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件查询合同列表 */
export const searchSelectContractListByPost = (params: SearchSelectContractList_In) =>
  axios.request<SearchSelectContractList_OutApiTableOut>({
    url: `/api/ContractOverseasIPRecord/SearchSelectContractList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据合同Id获取合同基本信息 */
export const getContractInfoByIdByPost = (params: GetContractInfoById_In) =>
  axios.request<Contract_Info>({
    url: `/api/ContractOverseasIPRecord/GetContractInfoById`,
    method: "post",
    params: {},
    data: params
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/ContractOverseasIPRecord/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
