/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import {
  SearchContractProductServiceInfoCollegeApplList_In,
  SearchContractProductServiceInfoCollegeApplList_OutApiTableOut,
  GetContractServiceInfoApplyInfoCollegeByApplId_Out,
  OperateContractProductServiceInfoCollegeAudit_In,
  SetCollegeContacts_In,
  SetContractServiceInfoCollegeContactsByApplyIds_In,
  GetContractServiceInfoCollegeByApplId_Out,
  GetContractServiceInfoCollegeByContractProductInfoId_Out,
  CheckHasSameValidContacts_In,
  CheckHasSameValidContacts_Out,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 根据查询条件获取合同服务信息慧思学院申请信息列表 */
export const searchContractProductServiceInfoCollegeApplListByPost = (
  params: SearchContractProductServiceInfoCollegeApplList_In
) =>
  axios.request<SearchContractProductServiceInfoCollegeApplList_OutApiTableOut>({
    url: `/api/ContractServiceInfoCollege/SearchContractProductServiceInfoCollegeApplList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据申请id获取合同服务申请信息_慧思学院信息 */
export const getContractServiceInfoApplyInfoCollegeByApplIdByPost = (params: { Id?: string }) =>
  axios.request<GetContractServiceInfoApplyInfoCollegeByApplId_Out>({
    url: `/api/ContractServiceInfoCollege/GetContractServiceInfoApplyInfoCollegeByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/** 撤销合同服务信息慧思学院申请审核信息 */
export const revokeContractProductServiceInfoCollegeAuditByPost = (
  params: OperateContractProductServiceInfoCollegeAudit_In
) =>
  axios.request<any>({
    url: `/api/ContractServiceInfoCollege/RevokeContractProductServiceInfoCollegeAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 作废合同服务信息慧思学院申请审核信息 */
export const voidContractProductServiceInfoCollegeAuditByPost = (
  params: OperateContractProductServiceInfoCollegeAudit_In
) =>
  axios.request<any>({
    url: `/api/ContractServiceInfoCollege/VoidContractProductServiceInfoCollegeAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 删除合同服务信息慧思学院申请信息 */
export const deleteContractProductServiceInfoCollegeAuditByPost = (
  params: OperateContractProductServiceInfoCollegeAudit_In
) =>
  axios.request<any>({
    url: `/api/ContractServiceInfoCollege/DeleteContractProductServiceInfoCollegeAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 设置慧思学院用户状信息 */
export const setCollegeContactsByPost = (params: SetCollegeContacts_In) =>
  axios.request<any>({
    url: `/api/ContractServiceInfoCollege/SetCollegeContacts`,
    method: "post",
    params: {},
    data: params
  });

/** 根据申请Id批量修改服务用户状态-启用/停用 */
export const setContractServiceInfoCollegeContactsByApplyIdsByPost = (
  params: SetContractServiceInfoCollegeContactsByApplyIds_In
) =>
  axios.request<any>({
    url: `/api/ContractServiceInfoCollege/SetContractServiceInfoCollegeContactsByApplyIds`,
    method: "post",
    params: {},
    data: params
  });

/** 根据申请id获取合同服务信息_慧思学院信息 */
export const getContractServiceInfoCollegeByApplIdByPost = (params: { Id?: string }) =>
  axios.request<GetContractServiceInfoCollegeByApplId_Out>({
    url: `/api/ContractServiceInfoCollege/GetContractServiceInfoCollegeByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据合同产品信息表id获取合同服务信息_慧思学院信息 */
export const getContractServiceInfoCollegeByContractProductInfoIdByPost = (params: { Id?: string }) =>
  axios.request<GetContractServiceInfoCollegeByContractProductInfoId_Out>({
    url: `/api/ContractServiceInfoCollege/GetContractServiceInfoCollegeByContractProductInfoId`,
    method: "post",
    params: params,
    data: {}
  });

/** 验证开通账号是否存在重复 */
export const checkHasSameValidContactsByPost = (params: CheckHasSameValidContacts_In) =>
  axios.request<CheckHasSameValidContacts_Out>({
    url: `/api/ContractServiceInfoCollege/CheckHasSameValidContacts`,
    method: "post",
    params: {},
    data: params
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/ContractServiceInfoCollege/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
