/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 根据查询条件获取合同服务信息邓白氏申请信息列表
 * @param {SearchContractProductServiceInfoDBApplList_In} params
 **/
export const searchContractProductServiceInfoDbApplListByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/SearchContractProductServiceInfoDBApplList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务申请信息_邓白氏信息
 * @param {Object} params
 * @param {string} params.applyId
 **/
export const getContractServiceApplInfoDbByApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/GetContractServiceApplInfoDBByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 撤销合同服务信息邓白氏申请审核信息
 * @param {OperateContractProductServiceInfoDBAudit_In} params
 **/
export const revokeContractProductServiceInfoDbAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/RevokeContractProductServiceInfoDBAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 作废合同服务信息邓白氏申请审核信息
 * @param {OperateContractProductServiceInfoDBAudit_In} params
 **/
export const voidContractProductServiceInfoDbAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/VoidContractProductServiceInfoDBAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除合同服务信息邓白氏申请审核信息
 * @param {OperateContractProductServiceInfoDBAudit_In} params
 **/
export const deleteContractProductServiceInfoDbAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/DeleteContractProductServiceInfoDBAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 添加邓白氏邮件模板信息
 * @param {FormData} params
 **/
export const addDbEmailTemplateByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/AddDBEmailTemplate`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改邓白氏邮件模板信息
 * @param {FormData} params
 **/
export const updateDbEmailTemplateByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/UpdateDBEmailTemplate`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除邓白氏邮件模板信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const deleteDbEmailTemplateByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/DeleteDBEmailTemplate`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据查询条件获取邓白氏邮件模板信息列表
 * @param {SearchDBEmailTemplateList_In} params
 **/
export const searchDbEmailTemplateListByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/SearchDBEmailTemplateList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据id获取邓白氏邮件模板信息列表
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getDbEmailTemplateByIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/GetDBEmailTemplateById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据申请id获取合同服务信息_邓白氏信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractServiceInfoDbByApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/GetContractServiceInfoDBByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同产品信息表id获取合同服务信息_邓白氏信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractServiceInfoDbByContractProductInfoIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/GetContractServiceInfoDBByContractProductInfoId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/ContractServiceInfo4DB/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
