/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 根据查询条件获取合同服务信息其他数据申请信息列表
 * @param {SearchContractProductServiceInfoOtherDataApplList_In} params
 **/
export const searchContractProductServiceInfoOtherDataApplListByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoOtherData/SearchContractProductServiceInfoOtherDataApplList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务申请信息_其他数据信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractServiceInfoApplyInfoOtherDataByApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoOtherData/GetContractServiceInfoApplyInfoOtherDataByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 撤销合同服务信息其他数据申请审核信息
 * @param {OperateContractProductServiceInfoOtherDataAudit} params
 **/
export const revokeContractProductServiceInfoOtherDataAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoOtherData/RevokeContractProductServiceInfoOtherDataAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 作废合同服务信息其他数据申请审核信息
 * @param {OperateContractProductServiceInfoOtherDataAudit} params
 **/
export const voidContractProductServiceInfoOtherDataAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoOtherData/VoidContractProductServiceInfoOtherDataAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除合同服务信息其他数据申请信息
 * @param {OperateContractProductServiceInfoOtherDataAudit} params
 **/
export const deleteContractProductServiceInfoOtherDataAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoOtherData/DeleteContractProductServiceInfoOtherDataAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务信息_其他数据信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractServiceInfoOtherDataByApplIdByPost = (params) =>
  axios.request({
    url: `/api/ContractServiceInfoOtherData/GetContractServiceInfoOtherDataByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/ContractServiceInfoOtherData/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
