/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import {
  AddContractPaperApply_In,
  UpdateContractPaperApply_In,
  SearchContractPaperApplyList_In,
  SearchContractPaperApplyList_OutApiTableOut,
  GetContractPaperApplyInfoById_Out,
  GetContractByContractPaperApplyId_In,
  GetContractByContractPaperApplyId_OutApiTableOut,
  GetContractPaperDistributeByContractPaperApplyId_In,
  GetContractPaperDistributeByContractPaperApplyId_OutApiTableOut,
  SearchContractPaperAuditList_In,
  SearchContractPaperAuditList_OutApiTableOut,
  AuditContractPaperApply_In,
  GetContractPaperTobeDistributeList_In,
  GetContractPaperTobeDistributeList_OutApiTableOut,
  GetContractPaperTobeDistributeDetailList_Out,
  GetContractPaperDistributeList_In,
  GetContractPaperDistributeList_OutApiTableOut,
  DistributeContractPaper_In,
  GetContractPaperEntitiesByRecipientId_Out,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 添加纸质合同申领信息 */
export const addContractPaperApplyByPost = (params: AddContractPaperApply_In) =>
  axios.request<any>({
    url: `/api/ContractPaper/AddContractPaperApply`,
    method: "post",
    params: {},
    data: params
  });

/** 修改纸质合同申领信息 */
export const updateContractPaperApplyByPost = (params: UpdateContractPaperApply_In) =>
  axios.request<any>({
    url: `/api/ContractPaper/UpdateContractPaperApply`,
    method: "post",
    params: {},
    data: params
  });

/** 删除纸质合同申领信息 */
export const deleteContractPaperApplyByPost = (params: { Ids?: string }) =>
  axios.request<any>({
    url: `/api/ContractPaper/DeleteContractPaperApply`,
    method: "post",
    params: params,
    data: {}
  });

/** 撤销纸质合同申领信息 */
export const revokeContractPaperApplyByPost = (params: { Ids?: string }) =>
  axios.request<any>({
    url: `/api/ContractPaper/RevokeContractPaperApply`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据查询条件获取纸质合同申领信息列表 */
export const searchContractPaperApplyListByPost = (params: SearchContractPaperApplyList_In) =>
  axios.request<SearchContractPaperApplyList_OutApiTableOut>({
    url: `/api/ContractPaper/SearchContractPaperApplyList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据纸质合同申领信息Id获取纸质合同申领信息 */
export const getContractPaperApplyInfoByIdByPost = (params: { Id?: string }) =>
  axios.request<GetContractPaperApplyInfoById_Out>({
    url: `/api/ContractPaper/GetContractPaperApplyInfoById`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据纸质合同申领id获取合同信息列表 */
export const getContractByContractPaperApplyIdByPost = (params: GetContractByContractPaperApplyId_In) =>
  axios.request<GetContractByContractPaperApplyId_OutApiTableOut>({
    url: `/api/ContractPaper/GetContractByContractPaperApplyId`,
    method: "post",
    params: {},
    data: params
  });

/** 根据纸质合同申领id获取纸质合同分发列表信息 */
export const getContractPaperDistributeByContractPaperApplyIdByPost = (
  params: GetContractPaperDistributeByContractPaperApplyId_In
) =>
  axios.request<GetContractPaperDistributeByContractPaperApplyId_OutApiTableOut>({
    url: `/api/ContractPaper/GetContractPaperDistributeByContractPaperApplyId`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件获取纸质合同申领信息列表 */
export const searchContractPaperAuditListByPost = (params: SearchContractPaperAuditList_In) =>
  axios.request<SearchContractPaperAuditList_OutApiTableOut>({
    url: `/api/ContractPaper/SearchContractPaperAuditList`,
    method: "post",
    params: {},
    data: params
  });

/** 审核纸质合同申领信息 */
export const auditContractPaperApplyByPost = (params: AuditContractPaperApply_In) =>
  axios.request<any>({
    url: `/api/ContractPaper/AuditContractPaperApply`,
    method: "post",
    params: {},
    data: params
  });

/** 撤销审核纸质合同申领信息 */
export const revokeAuditContractPaperApplyByPost = (params: { Ids?: string }) =>
  axios.request<any>({
    url: `/api/ContractPaper/RevokeAuditContractPaperApply`,
    method: "post",
    params: params,
    data: {}
  });

/** 作废审核纸质合同申领信息 */
export const voidAuditContractPaperApplyByPost = (params: { Ids?: string }) =>
  axios.request<any>({
    url: `/api/ContractPaper/VoidAuditContractPaperApply`,
    method: "post",
    params: params,
    data: {}
  });

/** 获取纸质合同待分发列表数据 */
export const getContractPaperTobeDistributeListByPost = (params: GetContractPaperTobeDistributeList_In) =>
  axios.request<GetContractPaperTobeDistributeList_OutApiTableOut>({
    url: `/api/ContractPaper/GetContractPaperTobeDistributeList`,
    method: "post",
    params: {},
    data: params
  });

/** 待分发列表页面头部纸质合同申领明细的合同版本及实发份数 */
export const getContractPaperTobeDistributeDetailListByPost = (params: { Id?: string }) =>
  axios.request<GetContractPaperTobeDistributeDetailList_Out[]>({
    url: `/api/ContractPaper/GetContractPaperTobeDistributeDetailList`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据申领Id获取已分发的纸质合同分发数据 */
export const getContractPaperDistributeListByPost = (params: GetContractPaperDistributeList_In) =>
  axios.request<GetContractPaperDistributeList_OutApiTableOut>({
    url: `/api/ContractPaper/GetContractPaperDistributeList`,
    method: "post",
    params: {},
    data: params
  });

/** 维护(新增保存或修改)纸质合同分发信息 */
export const distributeContractPaperByPost = (params: DistributeContractPaper_In[]) =>
  axios.request<any>({
    url: `/api/ContractPaper/DistributeContractPaper`,
    method: "post",
    params: {},
    data: params
  });

/** 根据纸质合同申领信息Id获取纸质合同申领信息 */
export const getContractPaperApplyInfoByAuditIdByPost = (params: { Id?: string }) =>
  axios.request<GetContractPaperApplyInfoById_Out>({
    url: `/api/ContractPaper/GetContractPaperApplyInfoByAuditId`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据纸质合同申领id获取合同信息列表 */
export const getContractByContractPaperAuditIdByPost = (params: GetContractByContractPaperApplyId_In) =>
  axios.request<GetContractByContractPaperApplyId_OutApiTableOut>({
    url: `/api/ContractPaper/GetContractByContractPaperAuditId`,
    method: "post",
    params: {},
    data: params
  });

/** 根据纸质合同申领id获取纸质合同分发列表信息 */
export const getContractPaperDistributeByContractPaperAuditIdByPost = (
  params: GetContractPaperDistributeByContractPaperApplyId_In
) =>
  axios.request<GetContractPaperDistributeByContractPaperApplyId_OutApiTableOut>({
    url: `/api/ContractPaper/GetContractPaperDistributeByContractPaperAuditId`,
    method: "post",
    params: {},
    data: params
  });

/** 获取当前用户可以使用的纸质合同号 */
export const getContractPaperEntitiesByRecipientIdByPost = (params: { contractPaperEntityId?: string }) =>
  axios.request<GetContractPaperEntitiesByRecipientId_Out[]>({
    url: `/api/ContractPaper/GetContractPaperEntitiesByRecipientId`,
    method: "post",
    params: params,
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/ContractPaper/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
