/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import { AddInvoicingDetails_In, InvoicingDetails_Out, Stream } from "./interface/index.ts";
import axios from "axios";

/** 添加合同发票开票明细信息 */
export const addInvoicingDetailsByPost = (params: AddInvoicingDetails_In[]) =>
  axios.request<any>({
    url: `/api/ContractInvoicingDetails/AddInvoicingDetails`,
    method: "post",
    params: {},
    data: params
  });

/** 获取合同发票开票明细信息 */
export const getInvoicingDetailsByPost = () =>
  axios.request<InvoicingDetails_Out[]>({
    url: `/api/ContractInvoicingDetails/GetInvoicingDetails`,
    method: "post",
    params: {},
    data: {}
  });

/** 获取合同发票开票明细信息全部包含删除 */
export const getInvoicingDetailsAllByPost = () =>
  axios.request<InvoicingDetails_Out[]>({
    url: `/api/ContractInvoicingDetails/GetInvoicingDetailsAll`,
    method: "post",
    params: {},
    data: {}
  });

/** 删除合同发票开票明细信息 */
export const deleteInvoicingDetailsByPost = (params: { id?: string }) =>
  axios.request<any>({
    url: `/api/ContractInvoicingDetails/DeleteInvoicingDetails`,
    method: "post",
    params: params,
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/ContractInvoicingDetails/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
