/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 添加合同说明模板申请信息
 * @param {AddContractTemplateApply_In} params
 **/
export const addContractTemplateApplyByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/AddContractTemplateApply`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改合同说明模板申请信息
 * @param {UpdateContractTemplateApply_In} params
 **/
export const updateContractTemplateApplyByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/UpdateContractTemplateApply`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除合同说明模板信息
 * @param {Object} params
 * @param {string} params.Ids
 **/
export const deleteContractTemplateByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/DeleteContractTemplate`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 撤销合同说明模板申请信息
 * @param {Object} params
 * @param {string} params.Ids
 **/
export const revokeContractTemplateApplyByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/RevokeContractTemplateApply`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据查询条件获取合同说明模板信息列表
 * @param {SearchContractTemplateList_In} params
 **/
export const searchContractTemplateListByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/SearchContractTemplateList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据合同说明模板信息Id获取合同说明模板信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractTemplateByIdByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/GetContractTemplateById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同说明模板id获取合同信息列表
 * @param {GetContractByContractTemplateId_In} params
 **/
export const getContractByContractTemplateIdByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/GetContractByContractTemplateId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取合同说明模板申请信息列表
 * @param {SearchContractTemplateApplyList_In} params
 **/
export const searchContractTemplateApplyListByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/SearchContractTemplateApplyList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据合同说明模板申请信息Id获取合同说明模板申请信息
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getContractTemplateApplyByIdByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/GetContractTemplateApplyById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 审核合同说明模板申请信息
 * @param {AuditContractTemplateApply_In} params
 **/
export const auditContractTemplateApplyByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/AuditContractTemplateApply`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 撤销合同说明模板申请审核信息
 * @param {Object} params
 * @param {string} params.Ids
 **/
export const revokeContractTemplateAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/RevokeContractTemplateAudit`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 作废合同说明模板申请信息
 * @param {Object} params
 * @param {string} params.Ids
 **/
export const voidContractTemplateAuditByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/VoidContractTemplateAudit`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 获取合同说明模板主键+描述，无分页
 * @param {GetUnlimitedContractTemplateList_In} params
 **/
export const getUnlimitedContractTemplateListByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/GetUnlimitedContractTemplateList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取用户当前可申请的最大模板数
 **/
export const getApplyCountUpLimitByPost = () =>
  axios.request({
    url: `/api/ContractTemplate/GetApplyCountUpLimit`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 根据服务年限筛选产品列表
 * @param {Object} params
 * @param {number} params.Cycle
 **/
export const getProductListByServiceCycleByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/GetProductListByServiceCycle`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据产品IdList获取服务年限，如果存在不同的服务年限，返回null
 * @param {GetServiceCycleByProductList_In} params
 **/
export const getServiceCycleByProductListByPost = (params) =>
  axios.request({
    url: `/api/ContractTemplate/GetServiceCycleByProductList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/ContractTemplate/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
