/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import {
  SearchContractProductServiceInfoDBApplList_In,
  SearchContractProductServiceInfoDBApplList_OutApiTableOut,
  GetContractServiceApplInfoDBByApplId_Out,
  OperateContractProductServiceInfoDBAudit_In,
  SearchDBEmailTemplateList_In,
  SearchDBEmailTemplateList_OutApiTableOut,
  GetDBEmailTemplateById_Out,
  GetContractServiceInfoDBByApplId_Out,
  GetContractServiceInfoDBByContractProductInfoId_Out,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 根据查询条件获取合同服务信息邓白氏申请信息列表 */
export const searchContractProductServiceInfoDbApplListByPost = (
  params: SearchContractProductServiceInfoDBApplList_In
) =>
  axios.request<SearchContractProductServiceInfoDBApplList_OutApiTableOut>({
    url: `/api/ContractServiceInfo4DB/SearchContractProductServiceInfoDBApplList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据申请id获取合同服务申请信息_邓白氏信息 */
export const getContractServiceApplInfoDbByApplIdByPost = (params: { applyId?: string }) =>
  axios.request<GetContractServiceApplInfoDBByApplId_Out>({
    url: `/api/ContractServiceInfo4DB/GetContractServiceApplInfoDBByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/** 撤销合同服务信息邓白氏申请审核信息 */
export const revokeContractProductServiceInfoDbAuditByPost = (params: OperateContractProductServiceInfoDBAudit_In) =>
  axios.request<any>({
    url: `/api/ContractServiceInfo4DB/RevokeContractProductServiceInfoDBAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 作废合同服务信息邓白氏申请审核信息 */
export const voidContractProductServiceInfoDbAuditByPost = (params: OperateContractProductServiceInfoDBAudit_In) =>
  axios.request<any>({
    url: `/api/ContractServiceInfo4DB/VoidContractProductServiceInfoDBAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 删除合同服务信息邓白氏申请审核信息 */
export const deleteContractProductServiceInfoDbAuditByPost = (params: OperateContractProductServiceInfoDBAudit_In) =>
  axios.request<any>({
    url: `/api/ContractServiceInfo4DB/DeleteContractProductServiceInfoDBAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 添加邓白氏邮件模板信息 */
export const addDbEmailTemplateByPost = (params: FormData) =>
  axios.request<any>({
    url: `/api/ContractServiceInfo4DB/AddDBEmailTemplate`,
    method: "post",
    params: {},
    data: params
  });

/** 修改邓白氏邮件模板信息 */
export const updateDbEmailTemplateByPost = (params: FormData) =>
  axios.request<any>({
    url: `/api/ContractServiceInfo4DB/UpdateDBEmailTemplate`,
    method: "post",
    params: {},
    data: params
  });

/** 删除邓白氏邮件模板信息 */
export const deleteDbEmailTemplateByPost = (params: { Id?: string }) =>
  axios.request<any>({
    url: `/api/ContractServiceInfo4DB/DeleteDBEmailTemplate`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据查询条件获取邓白氏邮件模板信息列表 */
export const searchDbEmailTemplateListByPost = (params: SearchDBEmailTemplateList_In) =>
  axios.request<SearchDBEmailTemplateList_OutApiTableOut>({
    url: `/api/ContractServiceInfo4DB/SearchDBEmailTemplateList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据id获取邓白氏邮件模板信息列表 */
export const getDbEmailTemplateByIdByPost = (params: { Id?: string }) =>
  axios.request<GetDBEmailTemplateById_Out>({
    url: `/api/ContractServiceInfo4DB/GetDBEmailTemplateById`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据申请id获取合同服务信息_邓白氏信息 */
export const getContractServiceInfoDbByApplIdByPost = (params: { Id?: string }) =>
  axios.request<GetContractServiceInfoDBByApplId_Out>({
    url: `/api/ContractServiceInfo4DB/GetContractServiceInfoDBByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据合同产品信息表id获取合同服务信息_邓白氏信息 */
export const getContractServiceInfoDbByContractProductInfoIdByPost = (params: { Id?: string }) =>
  axios.request<GetContractServiceInfoDBByContractProductInfoId_Out>({
    url: `/api/ContractServiceInfo4DB/GetContractServiceInfoDBByContractProductInfoId`,
    method: "post",
    params: params,
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/ContractServiceInfo4DB/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
