/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import {
  AddReceiptRegister_In,
  UpdateReceiptRegister_In,
  AuditContractReceiptRegister_In,
  GetTobeLockContractReceiptRegister_In,
  GetTobeLockContractReceiptRegister_Out,
  GetLockedContractReceiptRegister_In,
  GetLockedContractReceiptRegister_Out,
  ProjectInfoOtherItem_In,
  ProjectInfoOtherItemList_Out,
  ProjectInfoList_Out,
  MatchingRegistered_Out,
  SearchContractReceiptRegisterList_In,
  SearchContractReceiptRegisterList_OutApiTableOut,
  ReceiptRegister_Out,
  GetReceiptRegisterByContractId_In,
  GetReceiptRegisterByContractId_OutApiTableOut,
  GetReceiptRegisterByCustomerId_In,
  GetReceiptRegisterByCustomerId_OutApiTableOut,
  GetReceiptRegisterArrivalAmountInfoByContractId_Out,
  ContractReceiptRegisterInfo_Out,
  GetTobeConfirmedContractReceiptRegister_In,
  GetTobeConfirmedContractReceiptRegister_Out,
  GetConfirmedReceiptDetailsByContractId_Out,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 添加到账登记 */
export const addReceiptRegisterByPost = (params: AddReceiptRegister_In) =>
  axios.request<any>({
    url: `/api/ContractReceiptRegister/AddReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/** 修改到账登记 */
export const updateReceiptRegisterByPost = (params: UpdateReceiptRegister_In) =>
  axios.request<any>({
    url: `/api/ContractReceiptRegister/UpdateReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/** 到账登记复核 */
export const auditContractReceiptRegisterByPost = (params: AuditContractReceiptRegister_In) =>
  axios.request<any>({
    url: `/api/ContractReceiptRegister/AuditContractReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/** 获取待锁定到账登记信息 */
export const getTobeLockContractReceiptRegisterByPost = (params: GetTobeLockContractReceiptRegister_In) =>
  axios.request<GetTobeLockContractReceiptRegister_Out[]>({
    url: `/api/ContractReceiptRegister/GetTobeLockContractReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/** 获取已锁定到账登记信息 */
export const getLockedContractReceiptRegisterByPost = (params: GetLockedContractReceiptRegister_In) =>
  axios.request<GetLockedContractReceiptRegister_Out[]>({
    url: `/api/ContractReceiptRegister/GetLockedContractReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/** 锁定合同到账登记业绩审核信息 */
export const lockContractReceiptRegisterAchievementByPost = (params: string[]) =>
  axios.request<any>({
    url: `/api/ContractReceiptRegister/LockContractReceiptRegisterAchievement`,
    method: "post",
    params: {},
    data: params
  });

/** 解除锁定合同到账登记业绩审核信息 */
export const unLockContractReceiptRegisterAchievementByPost = (params: string[]) =>
  axios.request<any>({
    url: `/api/ContractReceiptRegister/UnLockContractReceiptRegisterAchievement`,
    method: "post",
    params: {},
    data: params
  });

/** 添加项目其他信息 */
export const addProjectInfoOtherItemByPost = (params: ProjectInfoOtherItem_In) =>
  axios.request<string>({
    url: `/api/ContractReceiptRegister/AddProjectInfoOtherItem`,
    method: "post",
    params: {},
    data: params
  });

/** 获取项目其他信息列表 */
export const getProjectInfoOtherItemListByPost = () =>
  axios.request<ProjectInfoOtherItemList_Out[]>({
    url: `/api/ContractReceiptRegister/GetProjectInfoOtherItemList`,
    method: "post",
    params: {},
    data: {}
  });

/** 获取项目信息列表 */
export const getProjectInfoListByPost = () =>
  axios.request<ProjectInfoList_Out[]>({
    url: `/api/ContractReceiptRegister/GetProjectInfoList`,
    method: "post",
    params: {},
    data: {}
  });

/** 根据匹配待登记Id获取匹配待登记信息 */
export const getMatchingRegisteredByIdByPost = (params: { id?: string }) =>
  axios.request<MatchingRegistered_Out>({
    url: `/api/ContractReceiptRegister/GetMatchingRegisteredById`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据匹配待登记Id拆分匹配待登记信息 */
export const splitMatchingRegisteredByIdByPost = (params: { id?: string }) =>
  axios.request<any>({
    url: `/api/ContractReceiptRegister/SplitMatchingRegisteredById`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据查询条件获取合同到账登记列表 */
export const searchContractReceiptRegisterListByPost = (params: SearchContractReceiptRegisterList_In) =>
  axios.request<SearchContractReceiptRegisterList_OutApiTableOut>({
    url: `/api/ContractReceiptRegister/SearchContractReceiptRegisterList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据到账登记Id获取到账登记信息 */
export const getReceiptRegisterByIdByPost = (params: { id?: string }) =>
  axios.request<ReceiptRegister_Out>({
    url: `/api/ContractReceiptRegister/GetReceiptRegisterById`,
    method: "post",
    params: params,
    data: {}
  });

/** 撤销到账登记，当确认状态为待确认、待复核、被驳回时，可返回上一个状态，返回后可重新进行操作。 */
export const revokeReceiptRegisterByPost = (params: { id?: string }) =>
  axios.request<any>({
    url: `/api/ContractReceiptRegister/RevokeReceiptRegister`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据合同id获取到账登记信息 */
export const getReceiptRegisterByContractIdByPost = (params: GetReceiptRegisterByContractId_In) =>
  axios.request<GetReceiptRegisterByContractId_OutApiTableOut>({
    url: `/api/ContractReceiptRegister/GetReceiptRegisterByContractId`,
    method: "post",
    params: {},
    data: params
  });

/** 根据客户id和到账日期获取到账登记信息 */
export const getReceiptRegisterByCustomerIdByPost = (params: GetReceiptRegisterByCustomerId_In) =>
  axios.request<GetReceiptRegisterByCustomerId_OutApiTableOut>({
    url: `/api/ContractReceiptRegister/GetReceiptRegisterByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/** 根据合同id获取回款金额和退款信息 */
export const getReceiptRegisterArrivalAmountInfoByContractIdByPost = (params: { contractId?: string }) =>
  axios.request<GetReceiptRegisterArrivalAmountInfoByContractId_Out>({
    url: `/api/ContractReceiptRegister/GetReceiptRegisterArrivalAmountInfoByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据到账登记表Id获取业绩确认详情信息（登记/复核用） */
export const getInfoByContractReceiptRegisterIdForAdminByPost = (params: { contractReceiptRegisterId?: string }) =>
  axios.request<ContractReceiptRegisterInfo_Out>({
    url: `/api/ContractReceiptRegister/GetInfoByContractReceiptRegisterIdForAdmin`,
    method: "post",
    params: params,
    data: {}
  });

/** 获取待确认到账登记信息 */
export const getTobeConfirmedContractReceiptRegisterByPost = (params: GetTobeConfirmedContractReceiptRegister_In) =>
  axios.request<GetTobeConfirmedContractReceiptRegister_Out[]>({
    url: `/api/ContractReceiptRegister/GetTobeConfirmedContractReceiptRegister`,
    method: "post",
    params: {},
    data: params
  });

/** 根据合同id获取已确认到账登记款项信息 */
export const getConfirmedReceiptDetailsByContractIdByPost = (params: { contractId?: string }) =>
  axios.request<GetConfirmedReceiptDetailsByContractId_Out[]>({
    url: `/api/ContractReceiptRegister/GetConfirmedReceiptDetailsByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/** 删除到账登记，当状态为待登记可进行操作 */
export const deleteReceiptRegisterByPost = (params: { id?: string; type?: number }) =>
  axios.request<any>({
    url: `/api/ContractReceiptRegister/DeleteReceiptRegister`,
    method: "post",
    params: params,
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/ContractReceiptRegister/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
