/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import {
  AuditContractProductServiceInfoGlobalSearchAppl_In,
  AuditContractProductServiceInfoCollegeAppl_In,
  AuditContractProductServiceInfoOtherDataAppl_In,
  SearchContractProductServiceInfoGtisAppl_IN,
  SearchContractProductServiceInfoGtisAppl_OUTApiTableOut,
  ContractServiceGtisInfo_OUT,
  ServiceInfoGtisUser_OUT,
  SetContractServiceInfoGtisUser_IN,
  SetContractServiceInfoGtisUserAll_IN,
  AuditContractProductServiceInfoGtisAppl_IN,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 审核合同服务信息邓白氏申请信息 */
export const auditContractProductServiceInfoDbApplByPost = (params: FormData) =>
  axios.request<any>({
    url: `/api/ContractProductService/AuditContractProductServiceInfoDBAppl`,
    method: "post",
    params: {},
    data: params
  });

/** 审核合同服务信息环球搜申请信息 */
export const auditContractProductServiceInfoGlobalSearchApplByPost = (
  params: AuditContractProductServiceInfoGlobalSearchAppl_In
) =>
  axios.request<any>({
    url: `/api/ContractProductService/AuditContractProductServiceInfoGlobalSearchAppl`,
    method: "post",
    params: {},
    data: params
  });

/** 审核合同服务信息慧思学院申请信息 */
export const auditContractProductServiceInfoCollegeApplByPost = (
  params: AuditContractProductServiceInfoCollegeAppl_In
) =>
  axios.request<any>({
    url: `/api/ContractProductService/AuditContractProductServiceInfoCollegeAppl`,
    method: "post",
    params: {},
    data: params
  });

/** 登记合同服务信息期刊邮寄的快递信息 */
export const registerContractProductServiceInfoMailingByPost = (params: FormData) =>
  axios.request<any>({
    url: `/api/ContractProductService/RegisterContractProductServiceInfoMailing`,
    method: "post",
    params: {},
    data: params
  });

/** 审核合同服务信息其他数据申请信息 */
export const auditContractProductServiceInfoOtherDataApplByPost = (
  params: AuditContractProductServiceInfoOtherDataAppl_In
) =>
  axios.request<any>({
    url: `/api/ContractProductService/AuditContractProductServiceInfoOtherDataAppl`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件获取合同服务信息环球慧思申请信息列表 */
export const searchContractProductServiceInfoGtisApplListByPost = (
  params: SearchContractProductServiceInfoGtisAppl_IN
) =>
  axios.request<SearchContractProductServiceInfoGtisAppl_OUTApiTableOut>({
    url: `/api/ContractProductService/SearchContractProductServiceInfoGtisApplList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据申请id获取合同服务信息_环球慧思信息（申请信息+在服信息） */
export const getContractServiceInfoGtisByApplIdByPost = (params: { applId?: string }) =>
  axios.request<ContractServiceGtisInfo_OUT>({
    url: `/api/ContractProductService/GetContractServiceInfoGtisByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据申请id获取环球慧思用户信息列表 */
export const getContractServiceInfoGtisUserByApplIdByPost = (params: { applId?: string }) =>
  axios.request<ServiceInfoGtisUser_OUT[]>({
    url: `/api/ContractProductService/GetContractServiceInfoGtisUserByApplId`,
    method: "post",
    params: params,
    data: {}
  });

/** 设置环球慧思用户状态信息(启用/停用) */
export const setContractServiceInfoGtisUserByPost = (params: SetContractServiceInfoGtisUser_IN) =>
  axios.request<any>({
    url: `/api/ContractProductService/SetContractServiceInfoGtisUser`,
    method: "post",
    params: {},
    data: params
  });

/** 启用/停用环球慧思产品中所有账户 */
export const setContractServiceInfoGtisUserAllByPost = (params: SetContractServiceInfoGtisUserAll_IN) =>
  axios.request<any>({
    url: `/api/ContractProductService/SetContractServiceInfoGtisUserAll`,
    method: "post",
    params: {},
    data: params
  });

/** 审核合同服务信息环球慧思申请信息 */
export const auditContractProductServiceInfoGtisApplByPost = (params: AuditContractProductServiceInfoGtisAppl_IN) =>
  axios.request<any>({
    url: `/api/ContractProductService/AuditContractProductServiceInfoGtisAppl`,
    method: "post",
    params: {},
    data: params
  });

/** 撤销合同服务信息环球慧思申请审核信息 10.9 gtis系统不支持撤销，暂时取消撤销功能 */
export const revokeContractProductServiceInfoGtisAuditByPost = (params: { applId?: string }) =>
  axios.request<any>({
    url: `/api/ContractProductService/RevokeContractProductServiceInfoGtisAudit`,
    method: "post",
    params: params,
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/ContractProductService/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
