/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 复制合同信息
 * @param {FormData} params
 **/
export const copyContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/CopyContract`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 添加合同信息
 * @param {FormData} params
 **/
export const addContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/AddContract`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 审核合同信息
 * @param {AuditContract_In} params
 **/
export const auditContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/AuditContract`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改合同信息
 * @param {FormData} params
 **/
export const updateContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/UpdateContract`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除合同信息，在合同状态为草稿、拒绝、作废时，合同可删除。
 * @param {Object} params
 * @param {string} params.ids
 **/
export const deleteContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/DeleteContract`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 作废合同信息，在合同状态为已提交、通过时，可作废。
 * @param {Object} params
 * @param {string} params.id
 **/
export const voidContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/VoidContract`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 撤销合同信息，在合同状态为已提交、通过时，才可撤销。
 * @param {Object} params
 * @param {string} params.id
 **/
export const revokeContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/RevokeContract`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同Id获取合同基本信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractBasicInfoByIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractBasicInfoById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同Id获取合同审核信息
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const getContractAuditInfoByContractIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractAuditInfoByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同Id获取合同审核历史信息
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const getContractAuditHistoryInfoByContractIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractAuditHistoryInfoByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据查询条件获取销售合同列表。
 * @param {SearchContractList_In} params
 **/
export const searchContractListByPost = (params) =>
  axios.request({
    url: `/api/Contract/SearchContractList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取销售合同审核列表。
 * @param {SearchContractList_In} params
 **/
export const searchContractAuditListByPost = (params) =>
  axios.request({
    url: `/api/Contract/SearchContractAuditList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 回收合同信息，在合同状态为（跟踪状态）签约、作废、退款时，才可回收合同。验证数据权限（合同创建者处理）。合同类型为纸质合同才存在回收，电子合同不需要回收。
 * @param {RecoveryContract_In} params
 **/
export const recoveryContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/RecoveryContract`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 确认合同信息
 * @param {ConfirmContract_In} params
 **/
export const confirmContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/ConfirmContract`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 添加合同服务信息环球慧思申请信息
 * @param {AddContractProductServiceInfoGtisAppl_In} params
 **/
export const addContractProductServiceInfoGtisApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/AddContractProductServiceInfoGtisAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务信息环球慧思申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractProductServiceInfoGtisApplByIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractProductServiceInfoGtisApplById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 添加合同服务信息邓白氏申请信息
 * @param {AddContractProductServiceInfoDBAppl_In} params
 **/
export const addContractProductServiceInfoDbApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/AddContractProductServiceInfoDBAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务信息邓白氏申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractProductServiceInfoDbApplByIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractProductServiceInfoDBApplById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 添加合同服务信息慧思学院申请信息
 * @param {AddContractProductServiceInfoCollegeAppl_In} params
 **/
export const addContractProductServiceInfoCollegeApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/AddContractProductServiceInfoCollegeAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务信息慧思学院申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractProductServiceInfoCollegeApplByIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractProductServiceInfoCollegeApplById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 添加合同服务信息环球搜申请信息
 * @param {AddContractProductServiceInfoGlobalSearchAppl_In} params
 **/
export const addContractProductServiceInfoGlobalSearchApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/AddContractProductServiceInfoGlobalSearchAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务信息环球搜申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractProductServiceInfoGlobalSearchApplByIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractProductServiceInfoGlobalSearchApplById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 添加合同服务信息其他数据申请信息
 * @param {AddContractProductServiceInfoOtherDataAppl_In} params
 **/
export const addContractProductServiceInfoOtherDataApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/AddContractProductServiceInfoOtherDataAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务信息其他数据申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractProductServiceInfoOtherDataApplByIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractProductServiceInfoOtherDataApplById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 添加合同服务信息项目信息申请信息
 * @param {AddContractProductServiceInfoProjectAppl_In} params
 **/
export const addContractProductServiceInfoProjectApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/AddContractProductServiceInfoProjectAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据申请id获取合同服务信息项目信息申请信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getContractProductServiceInfoProjectApplByIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractProductServiceInfoProjectApplById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同Id获取合同支付信息
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const getContractPaymentInfoByContractIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractPaymentInfoByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同Id获取合同产品信息
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const getContractProductInfoByContractIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractProductInfoByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据合同Id获取合同项目信息
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const getContractProjectInfoByContractIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractProjectInfoByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 添加合同服务信息
 * @param {AddContractProductServiceInfoAppl_In} params
 **/
export const addContractProductServiceInfoApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/AddContractProductServiceInfoAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据合同Id获取合同已开通服务信息
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const getContractServiceInfoByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractServiceInfo`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 变更合同服务信息环球慧思申请信息
 * @param {UpdateContractProductServiceInfoGtisAppl_In} params
 **/
export const updateContractProductServiceInfoGtisApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/UpdateContractProductServiceInfoGtisAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 变更合同服务信息环球搜申请信息
 * @param {UpdateContractProductServiceInfoGlobalSearchAppl_In} params
 **/
export const updateContractProductServiceInfoGlobalSearchApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/UpdateContractProductServiceInfoGlobalSearchAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 变更合同服务信息项目信息申请信息
 * @param {UpdateContractProductServiceInfoProjectAppl_In} params
 **/
export const updateContractProductServiceInfoProjectApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/UpdateContractProductServiceInfoProjectAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 变更合同服务信息其他数据申请信息
 * @param {UpdateContractProductServiceInfoOtherDataAppl_In} params
 **/
export const updateContractProductServiceInfoOtherDataApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/UpdateContractProductServiceInfoOtherDataAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 变更合同服务信息慧思学院申请信息
 * @param {UpdateContractProductServiceInfoCollegeAppl_In} params
 **/
export const updateContractProductServiceInfoCollegeApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/UpdateContractProductServiceInfoCollegeAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 变更合同服务信息邓白氏申请信息
 * @param {UpdateContractProductServiceInfoDBAppl_In} params
 **/
export const updateContractProductServiceInfoDbApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/UpdateContractProductServiceInfoDBAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据合同Id获取合同产品审核信息
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const getContractProductInfoAuditByContractIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractProductInfoAuditByContractId`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 添加合同信息变更申请信息
 * @param {FormData} params
 **/
export const addContractChangeApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/AddContractChangeAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取销售合同基本信息列表。
 * @param {SearchContractBasicInfoList_In} params
 **/
export const searchContractBasicInfoListByPost = (params) =>
  axios.request({
    url: `/api/Contract/SearchContractBasicInfoList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取到账登记销售合同基本信息列表
 * @param {SearchRegisterContractBasicInfoList_In} params
 **/
export const searchRegisterContractBasicInfoListByPost = (params) =>
  axios.request({
    url: `/api/Contract/SearchRegisterContractBasicInfoList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取合同变更申请信息列表
 * @param {SearchContractChangeAppl_IN} params
 **/
export const searchContractChangeApplListByPost = (params) =>
  axios.request({
    url: `/api/Contract/SearchContractChangeApplList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据合同变更Id获取合同变更信息
 * @param {Object} params
 * @param {string} params.auditId
 **/
export const getContractChangeApplByIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractChangeApplById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 审核合同变更申请信息
 * @param {AuditContractChangeAppl_IN} params
 **/
export const auditContractChangeApplByPost = (params) =>
  axios.request({
    url: `/api/Contract/AuditContractChangeAppl`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 撤销合同变更申请审核信息
 * @param {RevokeContractChangeAudit_IN} params
 **/
export const revokeContractChangeAuditByPost = (params) =>
  axios.request({
    url: `/api/Contract/RevokeContractChangeAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取合同可变更字段列表
 **/
export const getContractChangeColumnsByPost = () =>
  axios.request({
    url: `/api/Contract/GetContractChangeColumns`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 验证合同状态为通过
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const checkContractStateByPost = (params) =>
  axios.request({
    url: `/api/Contract/CheckContractState`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 设置合同催单
 * @param {FormData} params
 **/
export const addUrgeRegistrationByPost = (params) =>
  axios.request({
    url: `/api/Contract/AddUrgeRegistration`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 检测上传已盖章合同
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const checkUploadContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/CheckUploadContract`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 上传已盖章合同
 * @param {FormData} params
 **/
export const uploadContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/UploadContract`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取合同开通服务数量
 * @param {Object} params
 * @param {string} params.contractId
 **/
export const contractProductServiceInfoOpenedNumByPost = (params) =>
  axios.request({
    url: `/api/Contract/ContractProductServiceInfoOpenedNum`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据客户id和签约日期获取合同信息
 * @param {GetContractByCustomerId_In} params
 **/
export const getContractByCustomerIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 下载合同
 * @param {Object} params
 * @param {string} params.contractId
 * @param {number} params.type
 **/
export const downloadContractByPost = (params) =>
  axios.request({
    url: `/api/Contract/DownloadContract`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 合同详情 - 相关记录
 * @param {GetContractInfoRecords_In} params
 **/
export const getContractInfoRecordsByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractInfoRecords`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据合同id获取合同审核信息
 * @param {GetContractAuditByContractIdIn} params
 **/
export const getContractAuditByContractIdByPost = (params) =>
  axios.request({
    url: `/api/Contract/GetContractAuditByContractId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/Contract/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
