/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 客户控制器
 * @version v1
}
**/

import {
  AddSubCompany_INAddCustomer_IN,
  UpdateSubCompany_INUpdateCustomer_IN,
  QueryCustomer_IN,
  QueryCustomer_OUTApiTableOut,
  GetRetainCustomersNumber_IN,
  CustomerIdList_IN,
  ReleasePrivateCustomer_IN,
  TransferPrivateCustomer_IN,
  MergePrivateCustomer_IN,
  AddSubCompanyApply_IN,
  CommonCustomerId_IN,
  CustomerInfo_OUT,
  GetCustomerAuditInfo_IN,
  SearchCustomerAudit_OUTApiTableOut,
  CustomerId_IN,
  GetSubcompanyList,
  CustomerContractList_Out,
  CustomerRecord_IN,
  CustomerRecord_OUTApiTableOut,
  CustomerAchievementAbstract_OUT,
  GetUserCustomerAbstract_OUT,
  AddTempCustomer_IN,
  UpdateTempCustomer_IN,
  QueryTempCustomer_IN,
  QueryTempCustomer_OUTApiTableOut,
  TempCustomerIdList_IN,
  QueryCustomerGetHistory_OUT,
  TempCustomerRecord_IN,
  TempCustomerRecord_OUTApiTableOut,
  QueryTeamCustomer_IN,
  QueryTeamCustomer_OUTApiTableOut,
  CheckCustomer_IN,
  PreInspectionCustomer_OUT,
  AscriptionCustomer_OUT,
  QueryPublicCustomer_IN,
  QueryPublicCustomer_OUTApiTableOut,
  AssignPublicCustomer_IN,
  MergeCustomerAudit_IN,
  AddSubCompanyAudit_IN,
  SearchCustomerAudit_IN,
  GetCustomerAuditRecord_IN,
  GetCustomerAuditRecord_OUTApiTableOut,
  AuditId_IN,
  GetMergeCustomerAudit_OUT,
  GetSubCompanyAudit_OUT,
  SplitAddSubCompanyAudit_IN,
  SplitMergeCustomerAudit_IN,
  Company_OUT,
  SearchExportCustomer_IN,
  SearchExportCustomer_OUTApiTableOut,
  SearchExportCustomer_OUT,
  CustomerExportIdList_IN,
  SearchFairCustomer_IN,
  SearchFairCustomer_OUTApiTableOut,
  SearchFairCustomer_OUT,
  CustomerFairIdList_IN,
  Country_OUT,
  Province_OUT,
  City_OUT,
  CustomerIndustry_OUT,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 添加私有池客户 */
export const addPrivatePoolCustomerByPost = (params: AddSubCompany_INAddCustomer_IN) =>
  axios.request<string>({
    url: `/api/Customer/AddPrivatePoolCustomer`,
    method: "post",
    params: {},
    data: params
  });

/** 修改私有池客户（名称/代码不让改） */
export const updatePrivatePoolCustomerByPost = (params: UpdateSubCompany_INUpdateCustomer_IN) =>
  axios.request<any>({
    url: `/api/Customer/UpdatePrivatePoolCustomer`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件获取私有池客户信息列表 */
export const searchPrivatePoolCustomerListByPost = (params: QueryCustomer_IN) =>
  axios.request<QueryCustomer_OUTApiTableOut>({
    url: `/api/Customer/SearchPrivatePoolCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/** 获取当前用户的剩余可保留客户数量信息。系统可保留用户数量减去当前用户的已保留用户数量 */
export const getRetainCustomersNumberByPost = () =>
  axios.request<number>({
    url: `/api/Customer/GetRetainCustomersNumber`,
    method: "post",
    params: {},
    data: {}
  });

/** 获取所有用户的可保留数量 */
export const getAllUserRetainCustomersNumberByPost = (params: GetRetainCustomersNumber_IN) =>
  axios.request<number>({
    url: `/api/Customer/GetAllUserRetainCustomersNumber`,
    method: "post",
    params: {},
    data: params
  });

/** 将客户从私有池移入临时池 */
export const movePrivatePoolToTemporaryPoolByPost = (params: CustomerIdList_IN) =>
  axios.request<any>({
    url: `/api/Customer/MovePrivatePoolToTemporaryPool`,
    method: "post",
    params: {},
    data: params
  });

/** 将客户信息从私有池释放到公有池 */
export const releasePrivatePoolToPublicPoolByPost = (params: ReleasePrivateCustomer_IN) =>
  axios.request<any>({
    url: `/api/Customer/ReleasePrivatePoolToPublicPool`,
    method: "post",
    params: {},
    data: params
  });

/** 对私有池的客户信息进行延期操作，延长保护截止日期。 */
export const delayPrivatePoolByPost = (params: CustomerIdList_IN) =>
  axios.request<any>({
    url: `/api/Customer/DelayPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/** 移交私有客户 */
export const transferPrivatePoolByPost = (params: TransferPrivateCustomer_IN) =>
  axios.request<any>({
    url: `/api/Customer/TransferPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/** 合并私有客户 */
export const mergePrivatePoolApplyByPost = (params: MergePrivateCustomer_IN) =>
  axios.request<any>({
    url: `/api/Customer/MergePrivatePoolApply`,
    method: "post",
    params: {},
    data: params
  });

/** 添加子公司申请 */
export const addSubCompanyPrivatePoolApplyByPost = (params: AddSubCompanyApply_IN) =>
  axios.request<any>({
    url: `/api/Customer/AddSubCompanyPrivatePoolApply`,
    method: "post",
    params: {},
    data: params
  });

/** 根据id获取客户基本信息 */
export const getCustomerByIdByPost = (params: CommonCustomerId_IN) =>
  axios.request<CustomerInfo_OUT>({
    url: `/api/Customer/GetCustomerById`,
    method: "post",
    params: {},
    data: params
  });

/** 根据id获取客户审核记录（非管理人员用，验证客户权限） */
export const getCustomerAuditInfoByIdByPost = (params: GetCustomerAuditInfo_IN) =>
  axios.request<SearchCustomerAudit_OUTApiTableOut>({
    url: `/api/Customer/GetCustomerAuditInfoById`,
    method: "post",
    params: {},
    data: params
  });

/** 根据私有池客户Id获取公司名称列表 */
export const getSubcompanyListByCustomerIdByPost = (params: CustomerId_IN) =>
  axios.request<GetSubcompanyList[]>({
    url: `/api/Customer/GetSubcompanyListByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/** 获取私有池客户产品信息列表 */
export const getPrivateCustomerContractListByPost = (params: CustomerId_IN) =>
  axios.request<CustomerContractList_Out[]>({
    url: `/api/Customer/GetPrivateCustomerContractList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据客户Id获取相关记录（私有池/公有池） */
export const getRecordsByCustomerIdByPost = (params: CustomerRecord_IN) =>
  axios.request<CustomerRecord_OUTApiTableOut>({
    url: `/api/Customer/GetRecordsByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/** 根据客户业绩摘要 */
export const getCustomerAchievementAbstractByPost = (params: CustomerId_IN) =>
  axios.request<CustomerAchievementAbstract_OUT>({
    url: `/api/Customer/GetCustomerAchievementAbstract`,
    method: "post",
    params: {},
    data: params
  });

/** 获取私有池客户数量及昨日变化 */
export const getUserCustomerAbstrctByPost = () =>
  axios.request<GetUserCustomerAbstract_OUT>({
    url: `/api/Customer/GetUserCustomerAbstrct`,
    method: "post",
    params: {},
    data: {}
  });

/** 添加临时池客户 */
export const addTemporaryPoolCustomerByPost = (params: AddTempCustomer_IN) =>
  axios.request<any>({
    url: `/api/Customer/AddTemporaryPoolCustomer`,
    method: "post",
    params: {},
    data: params
  });

/** 维护临时池客户信息（名称/代码不让改） */
export const updateTemporaryPoolCustomerByPost = (params: UpdateTempCustomer_IN) =>
  axios.request<any>({
    url: `/api/Customer/UpdateTemporaryPoolCustomer`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件获取私有池客户信息列表 */
export const searchTemporaryPoolCustomerListByPost = (params: QueryTempCustomer_IN) =>
  axios.request<QueryTempCustomer_OUTApiTableOut>({
    url: `/api/Customer/SearchTemporaryPoolCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/** 移入私有池 */
export const moveTemporaryPoolToPrivatePoolByPost = (params: TempCustomerIdList_IN) =>
  axios.request<any>({
    url: `/api/Customer/MoveTemporaryPoolToPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/** 将客户信息从临时池删除 */
export const deleteTemporaryPoolByPost = (params: TempCustomerIdList_IN) =>
  axios.request<any>({
    url: `/api/Customer/DeleteTemporaryPool`,
    method: "post",
    params: {},
    data: params
  });

/** 获取公有池客户的领取历史记录 */
export const queryCustomerGetHistoryByPost = (params: CustomerId_IN) =>
  axios.request<QueryCustomerGetHistory_OUT[]>({
    url: `/api/Customer/QueryCustomerGetHistory`,
    method: "post",
    params: {},
    data: params
  });

/** 根据客户Id获取相关记录（临时池） */
export const getTempRecordsByCustomerIdByPost = (params: TempCustomerRecord_IN) =>
  axios.request<TempCustomerRecord_OUTApiTableOut>({
    url: `/api/Customer/GetTempRecordsByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件获取团队池客户信息列表 */
export const searchTeamPoolCustomerListByPost = (params: QueryTeamCustomer_IN) =>
  axios.request<QueryTeamCustomer_OUTApiTableOut>({
    url: `/api/Customer/SearchTeamPoolCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/** 预验客户 */
export const preInspectionCustomerListByPost = (params: CheckCustomer_IN) =>
  axios.request<PreInspectionCustomer_OUT[]>({
    url: `/api/Customer/PreInspectionCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/** 获取归属客户信息 */
export const ascriptionCustomerListByPost = (params: CheckCustomer_IN) =>
  axios.request<AscriptionCustomer_OUT[]>({
    url: `/api/Customer/AscriptionCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/** 查询列表 */
export const searchPublicPoolCustomerListByPost = (params: QueryPublicCustomer_IN) =>
  axios.request<QueryPublicCustomer_OUTApiTableOut>({
    url: `/api/Customer/SearchPublicPoolCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/** 获取私有池客户产品信息列表 */
export const getPublicCustomerContractListByPost = (params: CustomerId_IN) =>
  axios.request<CustomerContractList_Out[]>({
    url: `/api/Customer/GetPublicCustomerContractList`,
    method: "post",
    params: {},
    data: params
  });

/** 获取客户公有池剩余领取次数 */
export const publicPoolCollectSurplusTimesByPost = () =>
  axios.request<number>({
    url: `/api/Customer/PublicPoolCollectSurplusTimes`,
    method: "post",
    params: {},
    data: {}
  });

/** 领取公有池客户信息到私有池 */
export const collectPublicPoolToPrivatePoolByPost = (params: CustomerIdList_IN) =>
  axios.request<any>({
    url: `/api/Customer/CollectPublicPoolToPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/** 指派公有池客户信息到指定用户私有池 */
export const assignPublicPoolToPrivatePoolByPost = (params: AssignPublicCustomer_IN) =>
  axios.request<any>({
    url: `/api/Customer/AssignPublicPoolToPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/** 审核合并关系 */
export const mergePrivatePoolAuditByPost = (params: MergeCustomerAudit_IN) =>
  axios.request<any>({
    url: `/api/Customer/MergePrivatePoolAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 审核子公司关系 */
export const addSubCompanyPrivatePoolAuditByPost = (params: AddSubCompanyAudit_IN) =>
  axios.request<any>({
    url: `/api/Customer/AddSubCompanyPrivatePoolAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 查询审核列表 */
export const searchCustomerCompanyRelationshipAuditByPost = (params: SearchCustomerAudit_IN) =>
  axios.request<SearchCustomerAudit_OUTApiTableOut>({
    url: `/api/Customer/SearchCustomerCompanyRelationshipAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 查询客户审核历史记录 */
export const getCustomerAuditRecordsByPost = (params: GetCustomerAuditRecord_IN) =>
  axios.request<GetCustomerAuditRecord_OUTApiTableOut>({
    url: `/api/Customer/GetCustomerAuditRecords`,
    method: "post",
    params: {},
    data: params
  });

/** 获取合并客户审核详情 */
export const getMergeCustomerAuditInfoByPost = (params: AuditId_IN) =>
  axios.request<GetMergeCustomerAudit_OUT>({
    url: `/api/Customer/GetMergeCustomerAuditInfo`,
    method: "post",
    params: {},
    data: params
  });

/** 获取添加子公司审核详情 */
export const getAddSubCompanyAuditInfoByPost = (params: AuditId_IN) =>
  axios.request<GetSubCompanyAudit_OUT>({
    url: `/api/Customer/GetAddSubCompanyAuditInfo`,
    method: "post",
    params: {},
    data: params
  });

/** 拆分子公司 */
export const splitCompanyAuditByPost = (params: SplitAddSubCompanyAudit_IN) =>
  axios.request<any>({
    url: `/api/Customer/SplitCompanyAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 拆分合并客户 */
export const splitMergeCustomerAuditByPost = (params: SplitMergeCustomerAudit_IN) =>
  axios.request<any>({
    url: `/api/Customer/SplitMergeCustomerAudit`,
    method: "post",
    params: {},
    data: params
  });

/** 获取客户下的公司列表 */
export const searchCustomerCompanyListByPost = (params: CommonCustomerId_IN) =>
  axios.request<Company_OUT[]>({
    url: `/api/Customer/SearchCustomerCompanyList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件获取中国出口企业客户信息列表 */
export const searchExportCustomerListByPost = (params: SearchExportCustomer_IN) =>
  axios.request<SearchExportCustomer_OUTApiTableOut>({
    url: `/api/Customer/SearchExportCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/** 获取中出池客户详细信息 */
export const getExportCustomerByPost = (params: { id?: string }) =>
  axios.request<SearchExportCustomer_OUT>({
    url: `/api/Customer/GetExportCustomer`,
    method: "post",
    params: params,
    data: {}
  });

/** 领取中国出口客户信息到私有池 */
export const collectExportToPrivatePoolByPost = (params: CustomerExportIdList_IN) =>
  axios.request<any>({
    url: `/api/Customer/CollectExportToPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件获取广交会客户信息列表 */
export const searchFairCustomerListByPost = (params: SearchFairCustomer_IN) =>
  axios.request<SearchFairCustomer_OUTApiTableOut>({
    url: `/api/Customer/SearchFairCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/** 获取广交会客户信息 */
export const getFairCustomerByPost = (params: { id?: string }) =>
  axios.request<SearchFairCustomer_OUT>({
    url: `/api/Customer/GetFairCustomer`,
    method: "post",
    params: params,
    data: {}
  });

/** 领取广交会客户信息到私有池 */
export const collectFairToPrivatePoolByPost = (params: CustomerFairIdList_IN) =>
  axios.request<any>({
    url: `/api/Customer/CollectFairToPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/** 获取地址信息（国家） */
export const getAddressCountryByPost = () =>
  axios.request<Country_OUT[]>({
    url: `/api/Customer/GetAddress_Country`,
    method: "post",
    params: {},
    data: {}
  });

/** 获取地址信息（省） */
export const getAddressProvinceByPost = () =>
  axios.request<Province_OUT[]>({
    url: `/api/Customer/GetAddress_Province`,
    method: "post",
    params: {},
    data: {}
  });

/** 获取地址信息（市） */
export const getAddressCityByPost = () =>
  axios.request<City_OUT[]>({
    url: `/api/Customer/GetAddress_City`,
    method: "post",
    params: {},
    data: {}
  });

/** 获取主营产品和客户行业 */
export const getCustomerIndustryAndMainProductsByPost = () =>
  axios.request<CustomerIndustry_OUT[]>({
    url: `/api/Customer/GetCustomerIndustryAndMainProducts`,
    method: "post",
    params: {},
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/Customer/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
