/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 客户控制器
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 添加私有池客户
 * @param {AddSubCompany_INAddCustomer_IN} params
 **/
export const addPrivatePoolCustomerByPost = (params) =>
  axios.request({
    url: `/api/Customer/AddPrivatePoolCustomer`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改私有池客户（名称/代码不让改）
 * @param {UpdateSubCompany_INUpdateCustomer_IN} params
 **/
export const updatePrivatePoolCustomerByPost = (params) =>
  axios.request({
    url: `/api/Customer/UpdatePrivatePoolCustomer`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取私有池客户信息列表
 * @param {QueryCustomer_IN} params
 **/
export const searchPrivatePoolCustomerListByPost = (params) =>
  axios.request({
    url: `/api/Customer/SearchPrivatePoolCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取当前用户的剩余可保留客户数量信息。系统可保留用户数量减去当前用户的已保留用户数量
 **/
export const getRetainCustomersNumberByPost = () =>
  axios.request({
    url: `/api/Customer/GetRetainCustomersNumber`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 获取所有用户的可保留数量
 * @param {GetRetainCustomersNumber_IN} params
 **/
export const getAllUserRetainCustomersNumberByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetAllUserRetainCustomersNumber`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 将客户从私有池移入临时池
 * @param {CustomerIdList_IN} params
 **/
export const movePrivatePoolToTemporaryPoolByPost = (params) =>
  axios.request({
    url: `/api/Customer/MovePrivatePoolToTemporaryPool`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 将客户信息从私有池释放到公有池
 * @param {ReleasePrivateCustomer_IN} params
 **/
export const releasePrivatePoolToPublicPoolByPost = (params) =>
  axios.request({
    url: `/api/Customer/ReleasePrivatePoolToPublicPool`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 对私有池的客户信息进行延期操作，延长保护截止日期。
 * @param {CustomerIdList_IN} params
 **/
export const delayPrivatePoolByPost = (params) =>
  axios.request({
    url: `/api/Customer/DelayPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 移交私有客户
 * @param {TransferPrivateCustomer_IN} params
 **/
export const transferPrivatePoolByPost = (params) =>
  axios.request({
    url: `/api/Customer/TransferPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 合并私有客户
 * @param {MergePrivateCustomer_IN} params
 **/
export const mergePrivatePoolApplyByPost = (params) =>
  axios.request({
    url: `/api/Customer/MergePrivatePoolApply`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 添加子公司申请
 * @param {AddSubCompanyApply_IN} params
 **/
export const addSubCompanyPrivatePoolApplyByPost = (params) =>
  axios.request({
    url: `/api/Customer/AddSubCompanyPrivatePoolApply`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据id获取客户基本信息
 * @param {CommonCustomerId_IN} params
 **/
export const getCustomerByIdByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetCustomerById`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据id获取客户审核记录（非管理人员用，验证客户权限）
 * @param {GetCustomerAuditInfo_IN} params
 **/
export const getCustomerAuditInfoByIdByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetCustomerAuditInfoById`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据私有池客户Id获取公司名称列表
 * @param {CustomerId_IN} params
 **/
export const getSubcompanyListByCustomerIdByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetSubcompanyListByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取私有池客户产品信息列表
 * @param {CustomerId_IN} params
 **/
export const getPrivateCustomerContractListByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetPrivateCustomerContractList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据客户Id获取相关记录（私有池/公有池）
 * @param {CustomerRecord_IN} params
 **/
export const getRecordsByCustomerIdByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetRecordsByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据客户业绩摘要
 * @param {CustomerId_IN} params
 **/
export const getCustomerAchievementAbstractByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetCustomerAchievementAbstract`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取私有池客户数量及昨日变化
 **/
export const getUserCustomerAbstrctByPost = () =>
  axios.request({
    url: `/api/Customer/GetUserCustomerAbstrct`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 添加临时池客户
 * @param {AddTempCustomer_IN} params
 **/
export const addTemporaryPoolCustomerByPost = (params) =>
  axios.request({
    url: `/api/Customer/AddTemporaryPoolCustomer`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 维护临时池客户信息（名称/代码不让改）
 * @param {UpdateTempCustomer_IN} params
 **/
export const updateTemporaryPoolCustomerByPost = (params) =>
  axios.request({
    url: `/api/Customer/UpdateTemporaryPoolCustomer`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取私有池客户信息列表
 * @param {QueryTempCustomer_IN} params
 **/
export const searchTemporaryPoolCustomerListByPost = (params) =>
  axios.request({
    url: `/api/Customer/SearchTemporaryPoolCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 移入私有池
 * @param {TempCustomerIdList_IN} params
 **/
export const moveTemporaryPoolToPrivatePoolByPost = (params) =>
  axios.request({
    url: `/api/Customer/MoveTemporaryPoolToPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 将客户信息从临时池删除
 * @param {TempCustomerIdList_IN} params
 **/
export const deleteTemporaryPoolByPost = (params) =>
  axios.request({
    url: `/api/Customer/DeleteTemporaryPool`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取公有池客户的领取历史记录
 * @param {CustomerId_IN} params
 **/
export const queryCustomerGetHistoryByPost = (params) =>
  axios.request({
    url: `/api/Customer/QueryCustomerGetHistory`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据客户Id获取相关记录（临时池）
 * @param {TempCustomerRecord_IN} params
 **/
export const getTempRecordsByCustomerIdByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetTempRecordsByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取团队池客户信息列表
 * @param {QueryTeamCustomer_IN} params
 **/
export const searchTeamPoolCustomerListByPost = (params) =>
  axios.request({
    url: `/api/Customer/SearchTeamPoolCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 预验客户
 * @param {CheckCustomer_IN} params
 **/
export const preInspectionCustomerListByPost = (params) =>
  axios.request({
    url: `/api/Customer/PreInspectionCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取归属客户信息
 * @param {CheckCustomer_IN} params
 **/
export const ascriptionCustomerListByPost = (params) =>
  axios.request({
    url: `/api/Customer/AscriptionCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 查询列表
 * @param {QueryPublicCustomer_IN} params
 **/
export const searchPublicPoolCustomerListByPost = (params) =>
  axios.request({
    url: `/api/Customer/SearchPublicPoolCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取私有池客户产品信息列表
 * @param {CustomerId_IN} params
 **/
export const getPublicCustomerContractListByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetPublicCustomerContractList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取客户公有池剩余领取次数
 **/
export const publicPoolCollectSurplusTimesByPost = () =>
  axios.request({
    url: `/api/Customer/PublicPoolCollectSurplusTimes`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 领取公有池客户信息到私有池
 * @param {CustomerIdList_IN} params
 **/
export const collectPublicPoolToPrivatePoolByPost = (params) =>
  axios.request({
    url: `/api/Customer/CollectPublicPoolToPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 指派公有池客户信息到指定用户私有池
 * @param {AssignPublicCustomer_IN} params
 **/
export const assignPublicPoolToPrivatePoolByPost = (params) =>
  axios.request({
    url: `/api/Customer/AssignPublicPoolToPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 审核合并关系
 * @param {MergeCustomerAudit_IN} params
 **/
export const mergePrivatePoolAuditByPost = (params) =>
  axios.request({
    url: `/api/Customer/MergePrivatePoolAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 审核子公司关系
 * @param {AddSubCompanyAudit_IN} params
 **/
export const addSubCompanyPrivatePoolAuditByPost = (params) =>
  axios.request({
    url: `/api/Customer/AddSubCompanyPrivatePoolAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 查询审核列表
 * @param {SearchCustomerAudit_IN} params
 **/
export const searchCustomerCompanyRelationshipAuditByPost = (params) =>
  axios.request({
    url: `/api/Customer/SearchCustomerCompanyRelationshipAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 查询客户审核历史记录
 * @param {GetCustomerAuditRecord_IN} params
 **/
export const getCustomerAuditRecordsByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetCustomerAuditRecords`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取合并客户审核详情
 * @param {AuditId_IN} params
 **/
export const getMergeCustomerAuditInfoByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetMergeCustomerAuditInfo`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取添加子公司审核详情
 * @param {AuditId_IN} params
 **/
export const getAddSubCompanyAuditInfoByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetAddSubCompanyAuditInfo`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 拆分子公司
 * @param {SplitAddSubCompanyAudit_IN} params
 **/
export const splitCompanyAuditByPost = (params) =>
  axios.request({
    url: `/api/Customer/SplitCompanyAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 拆分合并客户
 * @param {SplitMergeCustomerAudit_IN} params
 **/
export const splitMergeCustomerAuditByPost = (params) =>
  axios.request({
    url: `/api/Customer/SplitMergeCustomerAudit`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取客户下的公司列表
 * @param {CommonCustomerId_IN} params
 **/
export const searchCustomerCompanyListByPost = (params) =>
  axios.request({
    url: `/api/Customer/SearchCustomerCompanyList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取中国出口企业客户信息列表
 * @param {SearchExportCustomer_IN} params
 **/
export const searchExportCustomerListByPost = (params) =>
  axios.request({
    url: `/api/Customer/SearchExportCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取中出池客户详细信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getExportCustomerByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetExportCustomer`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 领取中国出口客户信息到私有池
 * @param {CustomerExportIdList_IN} params
 **/
export const collectExportToPrivatePoolByPost = (params) =>
  axios.request({
    url: `/api/Customer/CollectExportToPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取广交会客户信息列表
 * @param {SearchFairCustomer_IN} params
 **/
export const searchFairCustomerListByPost = (params) =>
  axios.request({
    url: `/api/Customer/SearchFairCustomerList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取广交会客户信息
 * @param {Object} params
 * @param {string} params.id
 **/
export const getFairCustomerByPost = (params) =>
  axios.request({
    url: `/api/Customer/GetFairCustomer`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 领取广交会客户信息到私有池
 * @param {CustomerFairIdList_IN} params
 **/
export const collectFairToPrivatePoolByPost = (params) =>
  axios.request({
    url: `/api/Customer/CollectFairToPrivatePool`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取地址信息（国家）
 **/
export const getAddressCountryByPost = () =>
  axios.request({
    url: `/api/Customer/GetAddress_Country`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 获取地址信息（省）
 **/
export const getAddressProvinceByPost = () =>
  axios.request({
    url: `/api/Customer/GetAddress_Province`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 获取地址信息（市）
 **/
export const getAddressCityByPost = () =>
  axios.request({
    url: `/api/Customer/GetAddress_City`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 获取主营产品和客户行业
 **/
export const getCustomerIndustryAndMainProductsByPost = () =>
  axios.request({
    url: `/api/Customer/GetCustomerIndustryAndMainProducts`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/Customer/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
