/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import { Dictionary_Out, SearchDictionaryList_In, Dictionary_OutApiTableOut, Stream } from "./interface/index.ts";
import axios from "axios";

/** 根据数据字典Id获取数据字典信息 */
export const getDictionaryByIdByPost = (params: { Id?: string }) =>
  axios.request<Dictionary_Out>({
    url: `/api/Dictionary/GetDictionaryById`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据查询条件获取数据字典信息列表 */
export const searchDictionaryListByPost = (params: SearchDictionaryList_In) =>
  axios.request<Dictionary_OutApiTableOut>({
    url: `/api/Dictionary/SearchDictionaryList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据数据字典ParentId获取数据字典信息 */
export const getDictionaryByParentIdByPost = (params: { Id?: string }) =>
  axios.request<Dictionary_Out[]>({
    url: `/api/Dictionary/GetDictionaryByParentId`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据数据字典ParentName获取数据字典信息 */
export const getDictionaryByParentNameByPost = (params: { Name?: string }) =>
  axios.request<Dictionary_Out[]>({
    url: `/api/Dictionary/GetDictionaryByParentName`,
    method: "post",
    params: params,
    data: {}
  });

/** 根据数据字典ParentValue获取数据字典信息 */
export const getDictionaryByParentValueByPost = (params: { Value?: string }) =>
  axios.request<Dictionary_Out[]>({
    url: `/api/Dictionary/GetDictionaryByParentValue`,
    method: "post",
    params: params,
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/Dictionary/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
