/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 测试控制器
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 测试方法
 * @param {WeatherForecast_In} params - 传入的模型，里面涉及模型验证
 **/
export const testPostByPost = (params) =>
  axios.request({
    url: `/api/Example/TestPost`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 测试方法2
 * @param {WeatherForecast_In} params - 传入的模型，里面涉及模型验证
 **/
export const testPost2ByPost = (params) =>
  axios.request({
    url: `/api/Example/TestPost2`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 测试登录,返回token
 **/
export const loginByPost = () =>
  axios.request({
    url: `/api/Example/Login`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 测试下载
 **/
export const downLoadTestByPost = () =>
  axios.request({
    url: `/api/Example/DownLoadTest`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 测试上传
 * @param {FormData} params
 **/
export const uploadFileTestByPost = (params) =>
  axios.request({
    url: `/api/Example/UploadFileTest`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取请求和输出的ts模型
 * @param {Object} params
 * @param {string} params.url - 复制请求后面路由地址，粘贴此位置
 **/
export const getControllerMethodTsByGet = (params) =>
  axios.request({
    url: `/api/Example/GetControllerMethodTs`,
    method: "get",
    params: params,
    data: {}
  });

/**
 * @description 获取GUID
 * @param {Object} params
 * @param {number} params.number
 **/
export const getGuidByPost = (params) =>
  axios.request({
    url: `/api/Example/GetGuid`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description
 **/
export const getDictionaryTreeByPost = () =>
  axios.request({
    url: `/api/Example/GetDictionaryTree`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description
 * @param {LoginByPwd_In} params
 **/
export const loginAesTestByPost = (params) =>
  axios.request({
    url: `/api/Example/LoginAESTest`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description
 * @param {AddOrganization_In} params
 **/
export const addOrgestByPost = (params) =>
  axios.request({
    url: `/api/Example/AddOrgest`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description
 * @param {UpdateOrganization_In} params
 **/
export const updateOrgestByPost = (params) =>
  axios.request({
    url: `/api/Example/UpdateOrgest`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description
 **/
export const globalSearchApiTestByPost = () =>
  axios.request({
    url: `/api/Example/GlobalSearchAPITest`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description
 * @param {FormData} params
 **/
export const mailTestByPost = (params) =>
  axios.request({
    url: `/api/Example/MailTest`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description
 **/
export const mailReadTestByPost = () =>
  axios.request({
    url: `/api/Example/MailReadTest`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description
 * @param {Object} params
 * @param {string} params.formId
 **/
export const formRoleTestByPost = (params) =>
  axios.request({
    url: `/api/Example/FormRoleTest`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description
 **/
export const checkGitByPost = () =>
  axios.request({
    url: `/api/Example/CheckGit`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 添加用户
 * @param {BM_AddGtisUser} params
 **/
export const addUserByPost = (params) =>
  axios.request({
    url: `/api/Example/AddUser`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description
 **/
export const testGroupByByPost = () =>
  axios.request({
    url: `/api/Example/TestGroupBy`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/Example/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
