/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import { G4DbNames, Stream } from "./interface/index.ts";
import axios from "axios";

/** 获取Gtis国家信息 */
export const getG4DbNamesByPost = () =>
  axios.request<G4DbNames[]>({
    url: `/api/G4DbNames/GetG4DbNames`,
    method: "post",
    params: {},
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/G4DbNames/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
