/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import { SearchHsCodeList_In, SearchHsCodeList_OutApiTableOut, Stream } from "./interface/index.ts";
import axios from "axios";

/** 根据查询条件获取海关编码列表 */
export const searchHsCodeListByPost = (params: SearchHsCodeList_In) =>
  axios.request<SearchHsCodeList_OutApiTableOut>({
    url: `/api/HsCode/SearchHsCodeList`,
    method: "post",
    params: {},
    data: params
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/HsCode/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
