/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import {
  LoginByVerificationCode_In,
  GetVerificationCode_In,
  LoginByPwd_In,
  GetRetrievePwdVerificationCode_In,
  CheckRetrievePwdVerifyCode_In,
  RetrievePwdByVerifyCode_In,
  GetLoginBasicInfo_Out,
  Db_sys_form,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 通过手机号码/邮箱地址和验证码进行登录 */
export const loginByVerificationCodeByPost = (params: LoginByVerificationCode_In) =>
  axios.request<string>({
    url: `/api/Login/LoginByVerificationCode`,
    method: "post",
    params: {},
    data: params
  });

/** 获取手机号/邮箱号验证码 */
export const getVerificationCodeByPost = (params: GetVerificationCode_In) =>
  axios.request<any>({
    url: `/api/Login/GetVerificationCode`,
    method: "post",
    params: {},
    data: params
  });

/** 通过账号/手机号/Email和密码进行登录 */
export const loginByPwdByPost = (params: LoginByPwd_In) =>
  axios.request<string>({
    url: `/api/Login/LoginByPwd`,
    method: "post",
    params: {},
    data: params
  });

/** 通过微信扫码进行登录 */
export const loginByWeChartCodeByPost = (params: { code?: string }) =>
  axios.request<string>({
    url: `/api/Login/LoginByWeChartCode`,
    method: "post",
    params: params,
    data: {}
  });

/** 通过微信扫码绑定微信 */
export const bindWeChatByPost = (params: { code?: string }) =>
  axios.request<any>({
    url: `/api/Login/BindWeChat`,
    method: "post",
    params: params,
    data: {}
  });

/** 解除绑定微信 */
export const unBindWeChatByPost = () =>
  axios.request<any>({
    url: `/api/Login/UnBindWeChat`,
    method: "post",
    params: {},
    data: {}
  });

/** 密码找回--发送验证码 */
export const getRetrievePwdVerificationCodeByPost = (params: GetRetrievePwdVerificationCode_In) =>
  axios.request<any>({
    url: `/api/Login/GetRetrievePwdVerificationCode`,
    method: "post",
    params: {},
    data: params
  });

/** 找回密码--校验验证码 */
export const checkRetrievePwdVerifyCodeByPost = (params: CheckRetrievePwdVerifyCode_In) =>
  axios.request<any>({
    url: `/api/Login/CheckRetrievePwdVerifyCode`,
    method: "post",
    params: {},
    data: params
  });

/** 找回密码--重置密码 */
export const retrievePwdByVerifyCodeByPost = (params: RetrievePwdByVerifyCode_In) =>
  axios.request<any>({
    url: `/api/Login/RetrievePwdByVerifyCode`,
    method: "post",
    params: {},
    data: params
  });

/** 通过token获取用户基本信息(用户公钥) */
export const getLoginBasicInfoByPost = () =>
  axios.request<GetLoginBasicInfo_Out>({
    url: `/api/Login/GetLoginBasicInfo`,
    method: "post",
    params: {},
    data: {}
  });

/** 登录后根据token获取用户可操作的菜单 */
export const getFormMenusByUserIdByPost = () =>
  axios.request<Db_sys_form[]>({
    url: `/api/Login/GetFormMenusByUserId`,
    method: "post",
    params: {},
    data: {}
  });

/** 根据菜单Id获取可查看列表的集合 */
export const getFormTablesByMenuIdByPost = (params: { formTableId?: string }) =>
  axios.request<Db_sys_form[]>({
    url: `/api/Login/GetFormTablesByMenuId`,
    method: "post",
    params: params,
    data: {}
  });

export const checkGit2ByPost = () =>
  axios.request<any>({
    url: `/api/Login/CheckGit_2`,
    method: "post",
    params: {},
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/Login/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
