/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import { Stream } from "./interface/index.ts";
import axios from "axios";

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/MyControllerBase/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
