/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 添加发票原件信息
 * @param {AddOriginalInvoice_In} params
 **/
export const addOriginalInvoiceByPost = (params) =>
  axios.request({
    url: `/api/OriginalInvoice/AddOriginalInvoice`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改发票原件信息
 * @param {UpdateOriginalInvoice_In} params
 **/
export const updateOriginalInvoiceByPost = (params) =>
  axios.request({
    url: `/api/OriginalInvoice/UpdateOriginalInvoice`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除发票原件信息
 * @param {Object} params
 * @param {string} params.Ids
 **/
export const deleteOriginalInvoiceByPost = (params) =>
  axios.request({
    url: `/api/OriginalInvoice/DeleteOriginalInvoice`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据查询条件获取发票原件信息列表
 * @param {SearchOriginalInvoiceList_In} params
 **/
export const searchOriginalInvoiceListByPost = (params) =>
  axios.request({
    url: `/api/OriginalInvoice/SearchOriginalInvoiceList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据id获取发票原件信息列表
 * @param {Object} params
 * @param {string} params.Id
 **/
export const getOriginalInvoiceByIdByPost = (params) =>
  axios.request({
    url: `/api/OriginalInvoice/GetOriginalInvoiceById`,
    method: "post",
    params: params,
    data: {}
  });

/**
 * @description 根据发票原件信息id获取合同和发票信息列表
 * @param {GetContractAndInvoiceByOriginalInvoiceId_In} params
 **/
export const getContractAndInvoiceByOriginalInvoiceIdByPost = (params) =>
  axios.request({
    url: `/api/OriginalInvoice/GetContractAndInvoiceByOriginalInvoiceId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据开票公司、发票类型、发票形式获取未使用的发票实体，无分页
 * @param {GetOriginalInvoiceList_In} params
 **/
export const getOriginalInvoiceListByPost = (params) =>
  axios.request({
    url: `/api/OriginalInvoice/GetOriginalInvoiceList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/OriginalInvoice/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
