/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 业绩目标控制器
 * @version v1
}
**/

import {
  UpdatePerformanceObjectives_In,
  UpdatePerformanceObjectives_Out,
  GetPerformanceObjectivesList_In,
  GetPerformanceObjectivesList_Out,
  UnifiedConfigPerformanceObjectives_In,
  UnifiedConfigPerformanceObjectives_Out,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 修改业绩目标信息，主键为空，新建；主键不存在，删除；主键存在，修改； */
export const updatePerformanceObjectivesByPost = (params: UpdatePerformanceObjectives_In[]) =>
  axios.request<UpdatePerformanceObjectives_Out>({
    url: `/api/PerformanceObjectives/UpdatePerformanceObjectives`,
    method: "post",
    params: {},
    data: params
  });

/** 根据年份获取业绩目标信息 */
export const getPerformanceObjectivesListByPost = (params: GetPerformanceObjectivesList_In) =>
  axios.request<GetPerformanceObjectivesList_Out[]>({
    url: `/api/PerformanceObjectives/GetPerformanceObjectivesList`,
    method: "post",
    params: {},
    data: params
  });

/** 统一配置业绩目标信息 */
export const unifiedConfigPerformanceObjectivesByPost = (params: UnifiedConfigPerformanceObjectives_In[]) =>
  axios.request<UnifiedConfigPerformanceObjectives_Out>({
    url: `/api/PerformanceObjectives/UnifiedConfigPerformanceObjectives`,
    method: "post",
    params: {},
    data: params
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/PerformanceObjectives/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
