/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 晋升设置控制器
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 修改晋升信息，主键为空，新建；主键不存在，删除；主键存在，修改；
 * @param {UpdatePromotion_In} params
 **/
export const updatePromotionByPost = (params) =>
  axios.request({
    url: `/api/Promotion/UpdatePromotion`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据类别获取晋升信息
 * @param {GetPromotionList_In} params
 **/
export const getPromotionListByPost = (params) =>
  axios.request({
    url: `/api/Promotion/GetPromotionList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/Promotion/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
