/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 日程计划控制器
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 根据查询条件获取日程计划信息列表
 * @param {SearchScheduleList_In} params
 **/
export const searchScheduleListByPost = (params) =>
  axios.request({
    url: `/api/Schedule/SearchScheduleList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据日程计划Id获取日程计划信息
 * @param {GetScheduleById_In} params
 **/
export const getScheduleByIdByPost = (params) =>
  axios.request({
    url: `/api/Schedule/GetScheduleById`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据客户表主键Id获取日程计划信息
 * @param {GetScheduleByCustomerId_In} params
 **/
export const getScheduleByCustomerIdByPost = (params) =>
  axios.request({
    url: `/api/Schedule/GetScheduleByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据日程计划表主键Id设置日程计划为已读
 * @param {SetScheduleReadById_In} params
 **/
export const setScheduleReadByIdByPost = (params) =>
  axios.request({
    url: `/api/Schedule/SetScheduleReadById`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 添加日程计划信息
 * @param {FormData} params
 **/
export const addScheduleByPost = (params) =>
  axios.request({
    url: `/api/Schedule/AddSchedule`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改日程计划信息
 * @param {FormData} params
 **/
export const updateScheduleByPost = (params) =>
  axios.request({
    url: `/api/Schedule/UpdateSchedule`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除日程计划信息
 * @param {DeleteSchedule_In} params
 **/
export const deleteScheduleByPost = (params) =>
  axios.request({
    url: `/api/Schedule/DeleteSchedule`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 取消日程计划信息
 * @param {CancelSchedule_In} params
 **/
export const cancelScheduleByPost = (params) =>
  axios.request({
    url: `/api/Schedule/CancelSchedule`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 延期日程计划信息
 * @param {DelaySchedule_In} params
 **/
export const delayScheduleByPost = (params) =>
  axios.request({
    url: `/api/Schedule/DelaySchedule`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 完成日程计划信息
 * @param {FormData} params
 **/
export const completeScheduleByPost = (params) =>
  axios.request({
    url: `/api/Schedule/CompleteSchedule`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 通过年和月份字符串及一些查询条件返回该年月有日程计划的日期列表
 * @param {GetHasDataDatetimeByYearWithMonth_In} params - 年和月份字符串及一些查询条件
 **/
export const getHasDataDatetimeByYearWithMonthByPost = (params) =>
  axios.request({
    url: `/api/Schedule/GetHasDataDatetimeByYearWithMonth`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/Schedule/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
