/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 日程计划控制器
 * @version v1
}
**/

import {
  SearchScheduleList_In,
  SearchScheduleList_OutApiTableOut,
  GetScheduleById_In,
  GetScheduleById_Out,
  GetScheduleByCustomerId_In,
  GetScheduleByCustomerId_OutApiTableOut,
  SetScheduleReadById_In,
  SetScheduleReadById_Out,
  AddSchedule_Out,
  UpdateSchedule_Out,
  DeleteSchedule_In,
  DeleteSchedule_Out,
  CancelSchedule_In,
  CancelSchedule_Out,
  DelaySchedule_In,
  DelaySchedule_Out,
  CompleteSchedule_Out,
  GetHasDataDatetimeByYearWithMonth_In,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 根据查询条件获取日程计划信息列表 */
export const searchScheduleListByPost = (params: SearchScheduleList_In) =>
  axios.request<SearchScheduleList_OutApiTableOut>({
    url: `/api/Schedule/SearchScheduleList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据日程计划Id获取日程计划信息 */
export const getScheduleByIdByPost = (params: GetScheduleById_In) =>
  axios.request<GetScheduleById_Out>({
    url: `/api/Schedule/GetScheduleById`,
    method: "post",
    params: {},
    data: params
  });

/** 根据客户表主键Id获取日程计划信息 */
export const getScheduleByCustomerIdByPost = (params: GetScheduleByCustomerId_In) =>
  axios.request<GetScheduleByCustomerId_OutApiTableOut>({
    url: `/api/Schedule/GetScheduleByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/** 根据日程计划表主键Id设置日程计划为已读 */
export const setScheduleReadByIdByPost = (params: SetScheduleReadById_In) =>
  axios.request<SetScheduleReadById_Out>({
    url: `/api/Schedule/SetScheduleReadById`,
    method: "post",
    params: {},
    data: params
  });

/** 添加日程计划信息 */
export const addScheduleByPost = (params: FormData) =>
  axios.request<AddSchedule_Out>({
    url: `/api/Schedule/AddSchedule`,
    method: "post",
    params: {},
    data: params
  });

/** 修改日程计划信息 */
export const updateScheduleByPost = (params: FormData) =>
  axios.request<UpdateSchedule_Out>({
    url: `/api/Schedule/UpdateSchedule`,
    method: "post",
    params: {},
    data: params
  });

/** 删除日程计划信息 */
export const deleteScheduleByPost = (params: DeleteSchedule_In) =>
  axios.request<DeleteSchedule_Out>({
    url: `/api/Schedule/DeleteSchedule`,
    method: "post",
    params: {},
    data: params
  });

/** 取消日程计划信息 */
export const cancelScheduleByPost = (params: CancelSchedule_In) =>
  axios.request<CancelSchedule_Out>({
    url: `/api/Schedule/CancelSchedule`,
    method: "post",
    params: {},
    data: params
  });

/** 延期日程计划信息 */
export const delayScheduleByPost = (params: DelaySchedule_In) =>
  axios.request<DelaySchedule_Out>({
    url: `/api/Schedule/DelaySchedule`,
    method: "post",
    params: {},
    data: params
  });

/** 完成日程计划信息 */
export const completeScheduleByPost = (params: FormData) =>
  axios.request<CompleteSchedule_Out>({
    url: `/api/Schedule/CompleteSchedule`,
    method: "post",
    params: {},
    data: params
  });

/** 通过年和月份字符串及一些查询条件返回该年月有日程计划的日期列表 */
export const getHasDataDatetimeByYearWithMonthByPost = (params: GetHasDataDatetimeByYearWithMonth_In) =>
  axios.request<string[]>({
    url: `/api/Schedule/GetHasDataDatetimeByYearWithMonth`,
    method: "post",
    params: {},
    data: params
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/Schedule/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
