/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 统计控制器
 * @version v1
}
**/

import {
  OrgRankStatistics_IN,
  OrgRankStatistics_OUT,
  UserIndexStatistics_IN,
  SalesDataStatistics_OUT,
  UserIndexStatistics_OUT,
  SalesRankStatistics_OUT,
  SalesTargetStatistics_OUT,
  SalesFunnelStatistics_OUT,
  TrackingRecordRankStatistics_OUT,
  CustomerStatistics_OUT,
  ManagerReportStatistics_OUT,
  WeekWorkReportStatistics_OUT,
  MonthWorkReportStatistics_OUT,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 老系统的业绩排行统计 */
export const orgAchivementRankStatisticsByPost = (params: OrgRankStatistics_IN) =>
  axios.request<OrgRankStatistics_OUT[]>({
    url: `/api/Statistics/OrgAchivementRankStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 首页-销售业绩 */
export const salesDateStatisticsByPost = (params: UserIndexStatistics_IN) =>
  axios.request<SalesDataStatistics_OUT>({
    url: `/api/Statistics/SalesDateStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 用户主页相关统计值 */
export const getUserIndexStatisticsByPost = (params: UserIndexStatistics_IN) =>
  axios.request<UserIndexStatistics_OUT>({
    url: `/api/Statistics/GetUserIndexStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** （组织）首页-业绩排行 */
export const salesOrgRankStatisticsByPost = (params: UserIndexStatistics_IN) =>
  axios.request<SalesRankStatistics_OUT>({
    url: `/api/Statistics/SalesOrgRankStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** （个人）首页-业绩排行 */
export const salesUserRankStatisticsByPost = (params: UserIndexStatistics_IN) =>
  axios.request<SalesRankStatistics_OUT>({
    url: `/api/Statistics/SalesUserRankStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 首页-销售目标统计 */
export const salesTargetStatisticsByPost = (params: UserIndexStatistics_IN) =>
  axios.request<SalesTargetStatistics_OUT>({
    url: `/api/Statistics/SalesTargetStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 销售漏斗 */
export const salesFunnelStatisticsByPost = (params: UserIndexStatistics_IN) =>
  axios.request<SalesFunnelStatistics_OUT>({
    url: `/api/Statistics/SalesFunnelStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 跟踪排行 */
export const trackingRecordRankStatisticsByPost = (params: UserIndexStatistics_IN) =>
  axios.request<TrackingRecordRankStatistics_OUT>({
    url: `/api/Statistics/TrackingRecordRankStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 首页-客户统计(个人) */
export const customerStatisticsByPost = (params: UserIndexStatistics_IN) =>
  axios.request<CustomerStatistics_OUT>({
    url: `/api/Statistics/CustomerStatistics`,
    method: "post",
    params: {},
    data: params
  });

/** 管理日报用的统计 */
export const managerReportStatisticsByPost = () =>
  axios.request<ManagerReportStatistics_OUT>({
    url: `/api/Statistics/ManagerReportStatistics`,
    method: "post",
    params: {},
    data: {}
  });

/** 工作周报用的统计 */
export const weekWorkReportStatisticsByPost = () =>
  axios.request<WeekWorkReportStatistics_OUT>({
    url: `/api/Statistics/WeekWorkReportStatistics`,
    method: "post",
    params: {},
    data: {}
  });

/** 工作月报用的统计 */
export const monthWorkReportStatisticsByPost = () =>
  axios.request<MonthWorkReportStatistics_OUT>({
    url: `/api/Statistics/MonthWorkReportStatistics`,
    method: "post",
    params: {},
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/Statistics/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
