/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 统计控制器
 * @version v1
}
**/

import axios from "axios";

/**
 * @description 老系统的业绩排行统计
 * @param {OrgRankStatistics_IN} params
 **/
export const orgAchivementRankStatisticsByPost = (params) =>
  axios.request({
    url: `/api/Statistics/OrgAchivementRankStatistics`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 首页-销售业绩
 * @param {UserIndexStatistics_IN} params
 **/
export const salesDateStatisticsByPost = (params) =>
  axios.request({
    url: `/api/Statistics/SalesDateStatistics`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 用户主页相关统计值
 * @param {UserIndexStatistics_IN} params
 **/
export const getUserIndexStatisticsByPost = (params) =>
  axios.request({
    url: `/api/Statistics/GetUserIndexStatistics`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description （组织）首页-业绩排行
 * @param {UserIndexStatistics_IN} params
 **/
export const salesOrgRankStatisticsByPost = (params) =>
  axios.request({
    url: `/api/Statistics/SalesOrgRankStatistics`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description （个人）首页-业绩排行
 * @param {UserIndexStatistics_IN} params
 **/
export const salesUserRankStatisticsByPost = (params) =>
  axios.request({
    url: `/api/Statistics/SalesUserRankStatistics`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 首页-销售目标统计
 * @param {UserIndexStatistics_IN} params
 **/
export const salesTargetStatisticsByPost = (params) =>
  axios.request({
    url: `/api/Statistics/SalesTargetStatistics`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 销售漏斗
 * @param {UserIndexStatistics_IN} params
 **/
export const salesFunnelStatisticsByPost = (params) =>
  axios.request({
    url: `/api/Statistics/SalesFunnelStatistics`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 跟踪排行
 * @param {UserIndexStatistics_IN} params
 **/
export const trackingRecordRankStatisticsByPost = (params) =>
  axios.request({
    url: `/api/Statistics/TrackingRecordRankStatistics`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 首页-客户统计(个人)
 * @param {UserIndexStatistics_IN} params
 **/
export const customerStatisticsByPost = (params) =>
  axios.request({
    url: `/api/Statistics/CustomerStatistics`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 管理日报用的统计
 **/
export const managerReportStatisticsByPost = () =>
  axios.request({
    url: `/api/Statistics/ManagerReportStatistics`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 工作周报用的统计
 **/
export const weekWorkReportStatisticsByPost = () =>
  axios.request({
    url: `/api/Statistics/WeekWorkReportStatistics`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 工作月报用的统计
 **/
export const monthWorkReportStatisticsByPost = () =>
  axios.request({
    url: `/api/Statistics/MonthWorkReportStatistics`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/Statistics/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
