/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import { Db_crm_tianyancha_infoApiTableOut, Stream } from "./interface/index.ts";
import axios from "axios";

export const queryTianyanchaByPost = (params: { companyname?: string }) =>
  axios.request<Db_crm_tianyancha_infoApiTableOut>({
    url: `/api/Tianyancha/QueryTianyancha`,
    method: "post",
    params: params,
    data: {}
  });

export const queryTianyanchaListByPost = (params: { companyname?: string }) =>
  axios.request<Db_crm_tianyancha_infoApiTableOut>({
    url: `/api/Tianyancha/QueryTianyanchaList`,
    method: "post",
    params: params,
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/Tianyancha/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
