/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @fileDescription 跟踪记录控制器
 * @version v1
}
**/

import {
  SearchTrackingRecordList_In,
  SearchTrackingRecordList_OutApiTableOut,
  GetTrackingRecordById_In,
  GetTrackingRecordById_Out,
  GetTrackingRecordByCustomerId_In,
  GetTrackingRecordByCustomerId_OutApiTableOut,
  GetTrackingRecordNumberByCustomerId_In,
  GetTrackingRecordNumberByCustomerId_Out,
  SetTrackingRecordReadById_In,
  SetTrackingRecordReadById_Out,
  AddTrackingRecord_Out,
  UpdateTrackingRecord_Out,
  DeleteTrackingRecord_In,
  DeleteTrackingRecord_Out,
  SummaryTrackingRecordList_In,
  SummaryTrackingRecordList_OutApiTableOut,
  GetTrackingRecordByUserId_In,
  GetTrackingRecordByUserId_Out,
  TrackingRecord_SearchContractInfoIn,
  TrackingRecord_ContractInfo,
  Stream
} from "./interface/index.ts";
import axios from "axios";

/** 根据查询条件获取跟踪记录信息列表 */
export const searchTrackingRecordListByPost = (params: SearchTrackingRecordList_In) =>
  axios.request<SearchTrackingRecordList_OutApiTableOut>({
    url: `/api/TrackingRecord/SearchTrackingRecordList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据跟踪Id获取跟踪记录信息。 */
export const getTrackingRecordByIdByPost = (params: GetTrackingRecordById_In) =>
  axios.request<GetTrackingRecordById_Out>({
    url: `/api/TrackingRecord/GetTrackingRecordById`,
    method: "post",
    params: {},
    data: params
  });

/** 根据客户表主键Id获取跟踪记录信息。 */
export const getTrackingRecordByCustomerIdByPost = (params: GetTrackingRecordByCustomerId_In) =>
  axios.request<GetTrackingRecordByCustomerId_OutApiTableOut>({
    url: `/api/TrackingRecord/GetTrackingRecordByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/** 根据客户表主键Id获取客户追踪记录数量。 */
export const getTrackingRecordNumberByCustomerIdByPost = (params: GetTrackingRecordNumberByCustomerId_In) =>
  axios.request<GetTrackingRecordNumberByCustomerId_Out>({
    url: `/api/TrackingRecord/GetTrackingRecordNumberByCustomerId`,
    method: "post",
    params: {},
    data: params
  });

/** 根据追踪记录表主键Id设置追踪记录为已读。 */
export const setTrackingRecordReadByIdByPost = (params: SetTrackingRecordReadById_In) =>
  axios.request<SetTrackingRecordReadById_Out>({
    url: `/api/TrackingRecord/SetTrackingRecordReadById`,
    method: "post",
    params: {},
    data: params
  });

/** 添加跟踪记录信息 */
export const addTrackingRecordByPost = (params: FormData) =>
  axios.request<AddTrackingRecord_Out>({
    url: `/api/TrackingRecord/AddTrackingRecord`,
    method: "post",
    params: {},
    data: params
  });

/** 修改跟踪记录信息，验证是否本人创建的跟踪记录。 */
export const updateTrackingRecordByPost = (params: FormData) =>
  axios.request<UpdateTrackingRecord_Out>({
    url: `/api/TrackingRecord/UpdateTrackingRecord`,
    method: "post",
    params: {},
    data: params
  });

/** 删除跟踪记录信息，验证是否本人创建的跟踪记录，多条记录全部执行成功则返回成功，否则返回失败。只做逻辑删除，修改Deleted字段为1。 */
export const deleteTrackingRecordByPost = (params: DeleteTrackingRecord_In) =>
  axios.request<DeleteTrackingRecord_Out>({
    url: `/api/TrackingRecord/DeleteTrackingRecord`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件获取跟踪记录汇总信息列表 */
export const summaryTrackingRecordListByPost = (params: SummaryTrackingRecordList_In) =>
  axios.request<SummaryTrackingRecordList_OutApiTableOut>({
    url: `/api/TrackingRecord/SummaryTrackingRecordList`,
    method: "post",
    params: {},
    data: params
  });

/** 根据员工（用户）表主键Id获取跟踪记录信息 */
export const getTrackingRecordByUserIdByPost = (params: GetTrackingRecordByUserId_In) =>
  axios.request<GetTrackingRecordByUserId_Out[]>({
    url: `/api/TrackingRecord/GetTrackingRecordByUserId`,
    method: "post",
    params: {},
    data: params
  });

/** 根据查询条件查询合同列表 */
export const searchContractInfoByPost = (params: TrackingRecord_SearchContractInfoIn) =>
  axios.request<TrackingRecord_ContractInfo[]>({
    url: `/api/TrackingRecord/SearchContractInfo`,
    method: "post",
    params: {},
    data: params
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/TrackingRecord/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
