/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import { GetUserPromotionDescribeList_Out, Stream } from "./interface/index.ts";
import axios from "axios";

/** 获取员工职级描述列表 */
export const getUserPromotionDescribeListByPost = () =>
  axios.request<GetUserPromotionDescribeList_Out[]>({
    url: `/api/UserPromotionDescribe/GetUserPromotionDescribeList`,
    method: "post",
    params: {},
    data: {}
  });

/** 生成当前controller所有TypeScript模型 */
export const generateThisControllerModelToTsByPut = () =>
  axios.request<Stream>({
    url: `/api/UserPromotionDescribe/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
