/* eslint-disable */
// @ts-nocheck

/**
 * generated by free-swagger-core
 * @see https://www.npmjs.com/package/free-swagger
 * @title Crm2所有接口
 * @description 所有api
 * @version v1
}
**/

import axios from "axios";

/**
 * @description
 **/
export const reportTestByPost = () =>
  axios.request({
    url: `/api/WorkReports/ReportTest`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 根据查询条件获取工作日报列表。
 * @param {SearchWorkReportList_In} params
 **/
export const searchDailyWorkReportListByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/SearchDailyWorkReportList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据工作日报Id获取工作日报信息。
 * @param {WorkReportParameter_In} params
 **/
export const getDailyWorkReportByIdByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/GetDailyWorkReportById`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据用户Id获取工作日报信息提交列表。获取该用户组织下用户已提交报告和未提交报告的信息。
 **/
export const getDailyWorkReportSubmitStateByUserIdByPost = () =>
  axios.request({
    url: `/api/WorkReports/GetDailyWorkReportSubmitStateByUserId`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 添加工作日报信息。
 * @param {FormData} params
 **/
export const addDailyWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/AddDailyWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改工作日报信息。
 * @param {FormData} params
 **/
export const updateDailyWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/UpdateDailyWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除工作日报信息，当发布状态为草稿、已发送、已查阅时，可操作删除。
 * @param {WorkReportParameter_In} params
 **/
export const deleteDailyWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/DeleteDailyWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 撤销工作日报信息，当发布状态为已发送时，可撤销，支持多选操作。验证数据权限
 * @param {WorkReportParameter_In} params
 **/
export const revokeDailyWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/RevokeDailyWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 设置已读工作日报信息。验证数据权限。
 * @param {WorkReportParameter_In} params
 **/
export const setIsReadDailyWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/SetIsReadDailyWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取工作周报列表。
 * @param {SearchWorkReportList_In} params
 **/
export const searchWeekWorkReportListByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/SearchWeekWorkReportList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据工作周报Id获取工作周报信息。
 * @param {WorkReportParameter_In} params
 **/
export const getWeekWorkReportByIdByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/GetWeekWorkReportById`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据用户Id获取工作周报信息提交列表。获取该用户组织下用户已提交报告和未提交报告的信息。
 **/
export const getWeekWorkReportSubmitStateByUserIdByPost = () =>
  axios.request({
    url: `/api/WorkReports/GetWeekWorkReportSubmitStateByUserId`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 添加工作周报信息。
 * @param {FormData} params
 **/
export const addWeekWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/AddWeekWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改工作周报信息。
 * @param {FormData} params
 **/
export const updateWeekWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/UpdateWeekWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除工作周报信息，当发布状态为草稿、已发送、已查阅时，可操作删除
 * @param {WorkReportParameter_In} params
 **/
export const deleteWeekWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/DeleteWeekWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 撤销工作周报信息，当发布状态为已发送时，可撤销，支持多选操作。验证数据权限
 * @param {WorkReportParameter_In} params
 **/
export const revokeWeekWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/RevokeWeekWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 设置已读工作周报信息。验证数据权限。
 * @param {WorkReportParameter_In} params
 **/
export const setIsReadWeekWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/SetIsReadWeekWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取工作月报列表。
 * @param {SearchWorkReportList_In} params
 **/
export const searchMonthWorkReportListByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/SearchMonthWorkReportList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据工作月报Id获取工作月报信息。
 * @param {WorkReportParameter_In} params
 **/
export const getMonthWorkReportByIdByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/GetMonthWorkReportById`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据用户Id获取工作月报信息提交列表。获取该用户组织下用户已提交报告和未提交报告的信息。
 **/
export const getMonthWorkReportSubmitStateByUserIdByPost = () =>
  axios.request({
    url: `/api/WorkReports/GetMonthWorkReportSubmitStateByUserId`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 添加工作月报信息。
 * @param {FormData} params
 **/
export const addMonthWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/AddMonthWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改工作月报信息。保存草稿：添加工作月报信息，状态为草稿。新建：添加工作月报信息，状态为已发布。
 * @param {FormData} params
 **/
export const updateMonthWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/UpdateMonthWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除工作月报信息，当发布状态为草稿、已发送、已查阅时，可操作删除。
 * @param {WorkReportParameter_In} params
 **/
export const deleteMonthWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/DeleteMonthWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 撤销工作月报信息，当发布状态为已发送时，可撤销，支持多选操作。验证数据权限
 * @param {WorkReportParameter_In} params
 **/
export const revokeMonthWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/RevokeMonthWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 设置已读工作月报信息。验证数据权限。
 * @param {WorkReportParameter_In} params
 **/
export const setIsReadMonthWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/SetIsReadMonthWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取管理日报列表。
 * @param {SearchWorkReportList_In} params
 **/
export const searchManagerDailyWorkReportListByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/SearchManagerDailyWorkReportList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据管理日报Id获取管理日报信息。
 * @param {WorkReportParameter_In} params
 **/
export const getManagerDailyWorkReportByIdByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/GetManagerDailyWorkReportById`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据用户Id获取管理日报信息提交列表。获取该用户组织下用户已提交报告和未提交报告的信息。
 **/
export const getManagerDailyWorkReportSubmitStateByUserIdByPost = () =>
  axios.request({
    url: `/api/WorkReports/GetManagerDailyWorkReportSubmitStateByUserId`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 添加工作管理日报信息。
 * @param {FormData} params
 **/
export const addManagerDailyWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/AddManagerDailyWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改工作管理日报信息。
 * @param {FormData} params
 **/
export const updateManagerDailyWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/UpdateManagerDailyWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除管理工作日报信息，当发布状态为草稿、已发送、已查阅时，可操作删除。
 * @param {WorkReportParameter_In} params
 **/
export const deleteManagerDailyWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/DeleteManagerDailyWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 撤销管理工作日报信息，当发布状态为已发送时，可撤销，支持多选操作。验证数据权限
 * @param {WorkReportParameter_In} params
 **/
export const revokeManagerManagerDailyWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/RevokeManagerManagerDailyWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 设置已读管理工作日报信息。验证数据权限。
 * @param {WorkReportParameter_In} params
 **/
export const setIsReadManagerDailyWorkReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/SetIsReadManagerDailyWorkReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据查询条件获取工作简报列表。
 * @param {SearchWorkReportList_In} params
 **/
export const searchBriefReportListByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/SearchBriefReportList`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据工作简报Id获取工作简报信息。
 * @param {WorkReportParameter_In} params
 **/
export const getBriefReportByIdByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/GetBriefReportById`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 根据用户Id获取工作简报信息提交列表。获取该用户组织下用户已提交报告和未提交报告的信息。
 **/
export const getBriefReportSubmitStateByUserIdByPost = () =>
  axios.request({
    url: `/api/WorkReports/GetBriefReportSubmitStateByUserId`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 添加工作简报信息。
 * @param {FormData} params
 **/
export const addBriefReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/AddBriefReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 修改工作简报信息。
 * @param {FormData} params
 **/
export const updateBriefReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/UpdateBriefReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 删除工作简报信息
 * @param {WorkReportParameter_In} params
 **/
export const deleteBriefReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/DeleteBriefReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 撤销工作简报信息，当发布状态为已发送时，可撤销，支持多选操作。验证数据权限
 * @param {WorkReportParameter_In} params
 **/
export const revokeBriefReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/RevokeBriefReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 设置已读工作简报信息。验证数据权限。
 * @param {WorkReportParameter_In} params
 **/
export const setIsReadBriefReportByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/SetIsReadBriefReport`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取工作报告最新追踪信息
 * @param {WorkReportTypeParameter_In} params
 **/
export const getCustomerTraceRecordByPost = (params) =>
  axios.request({
    url: `/api/WorkReports/GetCustomerTraceRecord`,
    method: "post",
    params: {},
    data: params
  });

/**
 * @description 获取周报统计数据
 **/
export const weekWorkReportStatisticsByPost = () =>
  axios.request({
    url: `/api/WorkReports/WeekWorkReportStatistics`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 获取月报统计数据
 **/
export const monthWorkReportStatisticsByPost = () =>
  axios.request({
    url: `/api/WorkReports/MonthWorkReportStatistics`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 获取管理日报统计数据
 **/
export const managerReportStatisticsByPost = () =>
  axios.request({
    url: `/api/WorkReports/ManagerReportStatistics`,
    method: "post",
    params: {},
    data: {}
  });

/**
 * @description 根据当前登陆人员获取上级管理者ID及名字
 **/
export const getParentManagerUsersByPost = () =>
  axios.request({
    url: `/api/WorkReports/GetParentManagerUsers`,
    method: "post",
    params: {},
    data: {}
  });

/** 
 * @description 获取工作报告接收人(树形结构) 
 * @param {Object} params 
 * @param {number} params.workReportsType - EnumWorkReportsType: 
* `1` - Daily_日报
* `2` - Week_周报
* `3` - Month_月报
* `4` - Manager_管理日志
* `5` - Brief_简报
   
**/
export const getReportReciverUsersByGet = (params) =>
  axios.request({
    url: `/api/WorkReports/GetReportReciverUsers`,
    method: "get",
    params: params,
    data: {}
  });

/**
 * @description 生成当前controller所有TypeScript模型
 **/
export const generateThisControllerModelToTsByPut = () =>
  axios.request({
    url: `/api/WorkReports/GenerateThisControllerModelToTs`,
    method: "put",
    params: {},
    data: {}
  });
